### ISSUE TITLE
Add ability to transfer VHD as part of ARM Template deployment

### ISSUE THREAD

**Issue by jachin84** [Azure/azure-devtestlab#117]
Would it be possible to add the ability to transfer a VHD to the uploads folder as part of the ARM template. Ie. Specify a URI to a VHD in another storage account to transfer over. 

Otherwise I nee to deploy 1 ARM template to create the lab, execute some powershell to transfer a VHD, then deploy another ARM template to create a custom image from the uploaded VHD.

**Comment by gxy001** [comment]
Thanks for reporting this! It's a feature request rather than an issue. Would you mind opening a ticket at our UserVoice forum (where we collect votes from the community for feature requests)? 

Thanks!

Xiaoying Guo
Senior Program Manager, Azure DevTest Labs

**Comment by jachin84** [comment]
Will do.
