### ISSUE TITLE
linux-swapfile fails on CentOS-based 7.2

### ISSUE THREAD

**Issue by dls314** [Azure/azure-devtestlab#118]
I think it's failing because fallocate is creating a file with holes:
https://bugzilla.redhat.com/show_bug.cgi?id=1129205

However, the error message from swapon -fv is not consistent with that bug report. The error I get from swapon is below.

```
$ sudo swapon -fv /mnt/ZWQ1NGUzM2ZmMmE3OWVmOWI1OTYyOTNi
swapon /mnt/ZWQ1NGUzM2ZmMmE3OWVmOWI1OTYyOTNi
swapon: /mnt/ZWQ1NGUzM2ZmMmE3OWVmOWI1OTYyOTNi: found swap signature: version 1, page-size 4, same byte order
swapon: /mnt/ZWQ1NGUzM2ZmMmE3OWVmOWI1OTYyOTNi: pagesize=4096, swapsize=2147483648, devsize=2147483648
swapon: /mnt/ZWQ1NGUzM2ZmMmE3OWVmOWI1OTYyOTNi: swapon failed: Invalid argument
```

**Comment by dls314** [comment]
Recreating the swapfile with dd worked

**Comment by leovms** [comment]
Closed issue, as op identified the fix.
