### ISSUE TITLE
windows-download-sas-blob only supports anonymous access

### ISSUE THREAD

**Issue by gregpakes** [Azure/azure-devtestlab#148]
Unless I'm missing something, the windows-download-sas-blob artifact only supports anonymous access to blob storage.  It would be great if it supported SAS or account key access.

**Context**

I'm trying to follow this guide http://www.visualstudiogeeks.com/blog/DevOps/Use-VSTS-ReleaseManagement-to-Deploy-and-Test-in-AzureDevTestLabs but it seems to me the windows-download-sas-blob will only work if the container has public access enabled.  I'm not sure if I'm missing something though!

**Comment by leovms** [comment]
Thank you for your input. We welcome your contribution. If you already have updates to the artifact that you would like to contribute, we'd be happy to validate it and merge it into the public repo.

**Comment by drwill-ms** [comment]
In a private container using a little PowerShell, you can get a SAS URI for your blob with read permissions and use that URI instead.

I used the commands New-AzureStorageContext and New-AzureStorageBlobSASToken to get a SAS URI for a specific blob. You can use that output as your parameter.

You can get a SAS URI for any container/blob/etc in your storage account (filter with "SAS" in the storage account blade and follow the instructions). Be sure to update the URI generated to specify the full path to your desired file.

**Comment by ChrisMillsEu** [comment]
Please update the  description in Azure to state that the artifact only supports public containers.
Or update the artifact to fully support containers in azure blob storage ,including private containers.
Thank you

**Comment by drwill-ms** [comment]
It supports private containers with a SAS URI. You need to give the runner permissions some how, and creating a SAS URI is the best way to do that.
