### ISSUE TITLE
.NET Core Windows Server Hosting Artifact Missing

### ISSUE THREAD

**Issue by vanthome** [Azure/azure-devtestlab#159]
A corresponding artifact for this Microsoft Technology is be due I think ;)

https://docs.asp.net/en/latest/publishing/iis.html#install-the-net-core-windows-server-hosting-bundle

**Comment by gxy001** [comment]
@vanthome: Thanks for submitting the ticket. This GitHut repository is open to the community contribution, so you are very welcome to build such an artifact and send us a pull request. If you would like the artifact contributed by other people, please create your idea at https://feedback.azure.com/forums/320373-azure-devtest-labs, and we will prioritize it based on the community votes. Thanks!
