### ISSUE TITLE
Can you use standard Virtual Machine ARM Template options?

### ISSUE THREAD

**Issue by gregpakes** [Azure/azure-devtestlab#161]
When I create a new SQL IAAS VM, I am able to choose all sorts of SQL options, such as enabling SQL Authentication.  I want to use these in my DevTest VMs too.

I have looked at the ARM templates produced by the standard Virtual Machines blade.  Is this transferable into the DevTest VM ARM template?

**Comment by drwill-ms** [comment]
Not yet. We are working on a feature to deploy ARM templates to a lab instead of creating a VM directly. With that you can specify additional parameters to Compute to configure SQL, etc.
