### ISSUE TITLE
Artifact windows-ConfigurationManagerCurrentBranch(EVAL) is broken

### ISSUE THREAD

**Issue by slaet** [Azure/azure-devtestlab#165]
it seems that the ConfigMgr Artifact is not working anymore...
Artifact returns with the following error:
Unable to generate valid template for the artifact - Configuration Manager Current Branch with error(s) - Deployment template validation failed: 'The template variable '_commandToExecute' is not valid: Unable to parse template language expression 'concat('powershell.exe -ExecutionPolicy bypass -File SetupCMCB.ps1', ' -SiteCode ', parameters('SiteCode'), ' -SiteName ', , '", parameters('SiteName')), '"'': expected token 'Identifier' and actual 'Comma'. Please see https://aka.ms/arm-template-expressions for usage details..'.

**Comment by rzander** [comment]
Should be fixed now... please retry.

**Comment by ericame** [comment]
I am closing this issue as it has been fixed.

Thanks,
Erica
