### ISSUE TITLE
Artifact stuck on "installing"

### ISSUE THREAD

**Issue by gregpakes** [Azure/azure-devtestlab#166]
I am trying to use the **windows-download-sas-blob** artifact to download a file from a URL, but it is stuck on "Installing".  The logs are all completely empty too.

I have checked the following:

- Portal: Artifact blade just says "installing" and has no messages.  When it does eventually fail, there are no errors displayed.
- Filesystem: C:\WindowsAzure\Logs\Plugins\Microsoft.Compute.CustomScriptExtension\1.8\commandexecution_1.txt shows the following:

```
[11/11/2016 01:58:17.65] Executing: C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.8\enable.cmd 
[11/11/2016 01:58:19.29] Execution Complete.
######
Execution Output:
C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.8>if not exist RuntimeSettings\*.settings exit /b -2 
C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.8>start /B cmd /C bin\CustomScriptHandler.exe "enable" 


Execution Error:

######
Command C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.8\enable.cmd of Microsoft.Compute.CustomScriptExtension has exited with Exit code: 0
Plugin (name: Microsoft.Compute.CustomScriptExtension, version: 1.8) completed successfully.
```

Neither of which are very helpful.

I have tested the URL works and is accessible.

**Comment by ericame** [comment]
Hi @gregpakes, I am looking into these issues.

I see two separate problems here:
1. The windows-download-sas-blob artifact is not handling the error you're getting.
1. You're getting an error trying to run the artifact with your arguments.

To further debug the second issue, would you mind sharing what you put as the Destination File Path?

Thanks,
Erica

**Comment by gregpakes** [comment]
Hi,

It has been a long time since I looked at this, so I'll try and refresh my memory.

I believe the argument I used is a full path: c:\folder\file.ps1

thanks,

Greg

**Comment by ericame** [comment]
Hi @gregpakes, do you know what the size was of the file that you were trying to copy?

Thanks,
Erica

**Comment by gregpakes** [comment]
Its a powershell script of 3 lines.  Very small.

**Comment by drwill-ms** [comment]
This has been fixed.
