### ISSUE TITLE
problems with AD Join

### ISSUE THREAD

**Issue by chlsmith** [Azure/azure-devtestlab#184]
I have a Windows 2012 R2 machine I'm trying to get to join a domain using the AD Join artifact.  I've used this artifact in the past with Win10 successfully, but no matter what I'm using for my username/password combo, I'm getting the following:

"The resource operation completed with terminal provisioning state 'Failed'. VM has reported a failure when processing extension 'customScriptArtifact-1278997910'. Error message: "Failed to load settings from runtime settings file."."

**Comment by jaymarf** [comment]
Thank you for bringing this issue to our attention. I will file a bug and get the artifact updated as soon as possible.

**Comment by leovms** [comment]
A new domain join artifact is under review.
