### ISSUE TITLE
linux-vsts-build-agent Artifact?

### ISSUE THREAD

**Issue by stevenfollis** [Azure/azure-devtestlab#185]
Any plans to expand on the [windows-vsts-build-agent](https://github.com/Azure/azure-devtestlab/tree/master/Artifacts/windows-vsts-build-agent) Artifact to also include a Linux variation? 

Was using Ubuntu machines from a DTL to host VSTS Build Agents for Docker builds, and was sad to see that there wasn't a Linux option to automatically configure the VSTS agent. It wasn't too bad to setup by hand, but would have been lovely to use a DTL Artifact.

Could probably usethe VSTS section from the Azure Quickstart Template's [vsts-fullbuild-ubuntu-vm](https://github.com/Azure/azure-quickstart-templates/blob/master/vsts-fullbuild-ubuntu-vm/scripts/full-vstsbuild-install.sh#L142-L180) as a starting point.

Thanks!

**Comment by drwill-ms** [comment]
Hi Steven -

The windows VSTS build agent was provided by a member of the VSTS team, and updated recently by an internal user. We love community contributions, so if you'd like to publish one for Linux we'd be happy to accept it.

I will pass the request on to our PM team to prioritize it on the backlog, so if you or another community member doesn't get to it first, we will work on it when priority allows.

Thanks,
David

**Comment by Rurouni** [comment]
+1

**Comment by Evit15** [comment]
Hi drwill-ms,

Do you any update for this?
