### ISSUE TITLE
Windows TFS Test Agent like  artifact  (vstf_testagent)

### ISSUE THREAD

**Issue by kardinal3000** [Azure/azure-devtestlab#187]
Hello 
Would be great if you add [vstf_testagent](http://go.microsoft.com/fwlink/?LinkId=615472) like artifact 

In my workflow I use DevTest Labs tasks namely your task "AzureDtlCreateVM" and see that creating a new VM takes on average 9 minutes, from my custom VHD.  It is OK

What is not OK, is how long TFS's Test Agent installation takes. From what I got it is around 13 minutes on a good day. and up to 19 minutes on a bad one. This pushes overall provisioning time to at least 21 minutes!

 I think if I re-build my custom VHD  with  TestAgent pre-installed. It will help me to reduce the time  for  download and install  Test Agent  Of course I can do it myself, 
but I think if you add such artifact  in your repository it will be much better and useful

**Comment by mmydland** [comment]
Thanks for the feedback!   I agree that if you are looking to improve the installation time the best solution will be to include the Test Agent in your custom VHD.  It looks like the agents installers are available on chocolatey so you could use our Chocolatey artifact and pass the name of the package as an argument (e.g. visualstudio2015testagents or vs2013agents).   Would that be acceptable?

**Comment by kardinal3000** [comment]
@mmydland Thanks ! sounds good for me. I included Test Agent in my VHD. But I will try your advice use Chocolatey
