### ISSUE TITLE
DownloadFiles: Encountered an error while downloading files

### ISSUE THREAD

**Issue by kardinal3000** [Azure/azure-devtestlab#189]
Hello guys,
I got this error:  
> DownloadFiles: Encountered an error while downloading files. Cancelling download tasks. Exception: Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (404) Not Found. 

What I did, step by step:
1. I have three Storage Accounts in my DevTest lab. In one of them I put my PowerShell script (DevTest Labs > dtl name > storage account name > Blob service > artifacts)
2. Create new VM with artifact "Run PowerShell" (Use this to run a script using PowerShell ) 
- File URI(s): https://acautomation7462.blob.core.windows.net/artifacts/Run.ps1
- Script to Run: Run.ps1
- Script Arguments: -drive "d:\" -folderName "MyFolder"

Result:
![artifact - microsoft azure](https://cloud.githubusercontent.com/assets/18549964/22701233/c93a113c-ed65-11e6-86e1-838d374ccb93.png)

where I made mistakes?

**Comment by leovms** [comment]
I was unable to repro the steps. The File URI does not seem to be valid. Is this still an issue for you or did you manage to resolve it?

**Comment by drwill-ms** [comment]
Did you make the container public? Otherwise you need to create a SAS URI for the blob. The artifact will not have intrinsic access to the lab storage account. The process installing the artifact is a local VM admin, not an Azure Subscription admin.
