### ISSUE TITLE
Google Chrome on Windows 2016

### ISSUE THREAD

**Issue by tesharp** [Azure/azure-devtestlab#198]
Chrome installation fails on Windows Server 2016. It also references the googlechrome-allusers package in Chocolatey that is starting to get very old, and not approved.

After an hour and more it times out, with log saying:

```
[02/27/2017 09:17:06] ========== Configuration ==========
[02/27/2017 09:17:07] RawPackagesList : googlechrome-allusers
[02/27/2017 09:17:07] ========== Configuration ==========
[02/27/2017 09:17:07] Installing Chocolatey ...
WARNING: It's very likely you will need to close and reopen your shell 
  before you can use choco.
WARNING: You can safely ignore errors related to missing log files when 
  upgrading from a version of Chocolatey less than 0.9.9. 
  'Batch file could not be found' is also safe to ignore. 
  'The system cannot find the file specified' - also safe.
PATH environment variable does not have C:\ProgramData\chocolatey\bin in it. Adding...
[02/27/2017 09:17:15] Success.
[02/27/2017 09:17:15] Installing package: googlechrome-allusers ...
```

**Comment by stevenfollis** [comment]
Also experiencing the issue with Windows Server 2012 R2. 

Looks related to [6965a70fad53a1fbf3a0f727618e427b4d7758c0](https://github.com/Azure/azure-devtestlab/commit/6965a70fad53a1fbf3a0f727618e427b4d7758c0) by @mmydland 3 days ago?

**Comment by mmydland** [comment]
I will take a look.  We switched to the googlechrome-allusers package because the googlechrome package was failing checksum.

**Comment by mmydland** [comment]
Went back to the original package, but ignore the checksum since the url for the msi is not versioned and this will otherwise break periodically.  https://github.com/Azure/azure-devtestlab/commit/ff7697c60fd3c42941771a0d31641b6c957216cb

**Comment by stevenfollis** [comment]
Thanks @mmydland for the fast response! Validated that it's working again on my end. Appreciate it!
