### ISSUE TITLE
Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JArray'.

### ISSUE THREAD

**Issue by prasadwalwadkar** [Azure/azure-devtestlab#204]
We are trying to execute simple powershell script on newly created DevTestLab VM using this task (windows-run-powershell) in DevTestLab artifacts but getting below error.

Error message : Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JArray'.

Its was running till yesterday morning and suddenly stopped working.
Stopped working since 8th March.

**Comment by leovms** [comment]
Can you please provide more details? What were the parameters you passed to the artifact?

**Comment by drwill-ms** [comment]
Closing due to lack of response
