### ISSUE TITLE
Adding GitHub based Repository only uses master branch

### ISSUE THREAD

**Issue by marrobi** [Azure/azure-devtestlab#207]
Hello,

I've been trying to add a custom repo, using a branch of my fork of this repo. The "branchRef" property seems to be ignored and master is always shown. It also validates whatever branch I provide, via ARM Template or the portal.

Can anybody else replicate this?

Marcus

**Comment by iouri-s** [comment]
I could not replicate this. I set my repo to the "playground" branch and only the artifact from that branch showed up.
![capture](https://cloud.githubusercontent.com/assets/7333278/24052668/8bd94cf8-0af3-11e7-80f0-2ddccb60c12e.PNG)
![capture2](https://cloud.githubusercontent.com/assets/7333278/24052750/cd3cc472-0af3-11e7-9e1a-b2c42b21148f.PNG)

**Comment by marrobi** [comment]
Hmmm. Just tested the same way as you and it works . The artifact sub folder exists in master and the branch. I created a brand new artifact on my branch, and it doesn't appear. Does it read real time from GitHub when populating the list? I might be missing something, but still having the same issue.

Can you verify that if the folder, i.e. linux-apt-package, does not exist in master, just the branch that it works? My new artifacts only exist in the branch.

**Comment by iouri-s** [comment]
That also worked. If a new artifact is not showing up, it may be simply because Artifactfile.json is malformed. To eliminate this hypothesis, please copy Artifactfile.json from an existing artifact into the new folder and just update the title, to make sure you can distinguish it in the list.

**Comment by marrobi** [comment]
Something isn't right. The json is fine as it does show eventually. Just had one that wouldn't display. I had to change the repo branch to master, it showed then switched it back to my custom branch and it stayed. Is there some caching going on of the artifact list?

**Comment by leovms** [comment]
Marcus, apologies for the long delay getting back to you on this issue. Can you please tell me if this is still an issue for you? If so, I'd like to offer we try to resolve it offline. We can come back and update the resolution after. Let me know and we can set up a session.
