### ISSUE TITLE
windows-download-sas-blob: Artifact errors when running cmdlet ./downloadFile.ps1

### ISSUE THREAD

**Issue by marchel2** [Azure/azure-devtestlab#211]
I've created a new DevTest Lab VM along with the 'windows-download-sas-blob' artifact.

When applying artifacts, i get the following error(from portal):

![image](https://cloud.githubusercontent.com/assets/5473445/24718726/ab056a36-19fc-11e7-8682-002d6e69bd2f.png)

Not sure if related but, this [commit](https://github.com/Azure/azuredevtestlab/commit/e9d459103cabe7279312dc7dd25e330dcca073c9) changed the cmdlet reference from './artifact.ps1' to './downloadFile.ps1'

**Comment by leovms** [comment]
Thank you for reporting this. It does indeed look like we have updated the definition to point to another PS file. Let us make the corrections and ensure the artifact is working again. I will update this issue when done so you can try it again.

**Comment by leovms** [comment]
The issue has been fixed. Please try it again and let us know if you are now unblocked. We apologize for the inconvenience. Feel free to reopen the issue if the problem persists.
