### ISSUE TITLE
Disconnect between DevTest Lab and the Azure File Copy VSTS task

### ISSUE THREAD

**Issue by gregpakes** [Azure/azure-devtestlab#215]
I'm not sure whether this should be in this repo or in the https://github.com/Microsoft/vsts-tasks.

## Scenario

- I am using DevTest lab to create 5 machines.
- I am using the *Advanced Settings* -> *Number of instances* feature.
- This creates each VM in a separate Resource Group.
- I am then trying to deploy files to all of the VMs using the VSTS task Azure File Copy.  This task requires a resource group that contains all the machines.  DevTest lab doesn't give me one, so I can't use this task.

Is there any way around this other than using the File Copy task multiple times (once for each machine)?

I also tried moving all the VMs into a single resource group, but I get an error saying that managed disks can't be moved.

**Comment by gregpakes** [comment]
The same issue can be seen with the **Azure Resource Group Deployment** task.

This task allows you to start all VMs within a resource group.  If I choose the devtest lab resource group, it states:

> Resource group XXXX has no machines in it

**Comment by drwill-ms** [comment]
Unfortunately, the way the lab is designed at this point makes it incompatible with these other Azure integrations. However, we do have a plan on the backlog to create all Lab VMs in the same resource group which should make these scenarios work.

Note, for the "number of instances" feature, if Shared IP is used, the VMs should be put into the same resource group.
