### ISSUE TITLE
Improve artifact output when choco install fails

### ISSUE THREAD

**Issue by workleodig** [Azure/azure-devtestlab#227]
The output received when an artifact fails to install a choco package does not contain enough details for the owner to take action. For example, a user applied the windows-ssms artifact from the public repo. When it failed the console output looked like this:

WinRM is already set up to receive requests on this computer.
WinRM is already set up for remote management on this computer.
[05/10/2017 13:19:03] ========== Configuration ==========
[05/10/2017 13:19:03] RawPackagesList : sql-server-management-studio
[05/10/2017 13:19:03] ========== Configuration ==========
[05/10/2017 13:19:03] Installing Chocolatey ...
WARNING: It's very likely you will need to close and reopen your shell 
  before you can use choco.
WARNING: You can safely ignore errors related to missing log files when 
  upgrading from a version of Chocolatey less than 0.9.9. 
  'Batch file could not be found' is also safe to ignore. 
  'The system cannot find the file specified' - also safe.
[05/10/2017 13:19:08] Success.
[05/10/2017 13:19:08] Installing package: sql-server-management-studio ...
ERROR: Installation failed. **Please see the chocolatey logs in %ALLUSERSPROFILE%\chocolatey\logs folder for details.**

The user then has to log into the VM and search through the logs folder to determine why the artifact failed. It would be nice if the artifact output were more actionable and said something like "Install is not supported on Win2008" or "Install failed because SSMS is already installed". 

The choco package logs contain the details users need to know. It would be nice if the artifacts surfaced this to users more conveniently.

**Comment by leovms** [comment]
Thank you for the feedback. It is a good idea. Let me take a look and evaluate the effort.

**Comment by petehauge** [comment]
I have an extra artifact 'get logs' that runs the following code - would be great to include this in the chocolatey artifacts directly:
`# Get the latest log directory
$dirs = Get-ChildItem $env:ALLUSERSPROFILE -Directory "Chocolatey*" | Sort-Object LastWriteTime -Descending

if ($dirs.Length -eq 0) {
	Write-Error "Unable to find chocolatey logs here: $env:ALLUSERSPROFILE "
}

# found a dir, get files from the latest
$files = Get-ChildItem $dirs[0].FullName "*.log" -Recurse

foreach ($file in $files) {
	Get-Content $file.FullName | Write-Output
}
`

**Comment by leovms** [comment]
Thank you for the contribution. At this time, we are investigating an issue where large logs get truncated. We're reaching out to the team responsible for the CustomScriptExtension to identify resolution.

**Comment by leovms** [comment]
We have consulted with the CustomScriptExtension team and they have confirmed they only output the last 4K from stdout / stderr. Because of this limitation, outputting entire logs will not be feasible.
