### ISSUE TITLE
Template Parameters parsing doesn't work

### ISSUE THREAD

**Issue by gregpakes** [Azure/azure-devtestlab#229]
I am trying to make use of the expiration date feature in Dev Test labs.  However, rather than setting a fixed date, I wanted to set a sliding date (14 days from now).

I wanted to pass this into the Create DevTest VM task via the "Template Parameters".   I added the parameter into my json ARM template and expected that i could populate it from the Template Parameters option within the create task, like so:

```
-newVMName '$(Release.ReleaseName)' -userName '$(vmUsername)' -password (ConvertTo-SecureString -String '$(vmPassword)' -AsPlainText -Force) -expirationDate ((Get-Date).AddDays(14).ToString("o"))
```

Is this supported?

**Comment by drwill-ms** [comment]
Not supported, but a feature we already have on our backlog. We especially need this for formulas.
