### ISSUE TITLE
Artifact shows as successful even if powershell errors

### ISSUE THREAD

**Issue by gregpakes** [Azure/azure-devtestlab#230]
The **windows-vsts-download-and-run-script** artifact shows as successful, even if the powershell script to run fails.

I would expect that to cause the artifact to fail.

**Comment by leovms** [comment]
Thank you for reporting this issue. The artifact needs to be updated to correctly bubble up errors. I'm bringing the issue internally to get resolved. We'll update here when done.

**Comment by leovms** [comment]
We've updated the artifact to provide better logging and error handling. Please try it and let us know if you still have issues.
