### ISSUE TITLE
Accessing secrets from ARM templates doesn't work for me

### ISSUE THREAD

**Issue by gregpakes** [Azure/azure-devtestlab#231]
I am trying to access secrets in the ARM template by following the guide here: 

https://azure.microsoft.com/en-us/updates/azure-devtest-labs-keep-your-secrets-safe-and-easy-to-use-with-the-new-personal-secret-store/

It says:

> In addition to creating VMs and using artifacts, you can save your secret name with formulas and Azure Resource Manager templates. Here's an example of how it's used in a Resource Manager template to provision a new lab VM

However it does not seem to work for me.

I am trying to use the **windows-vsts-download-and-run-script** artifact.  I am trying to pull the Personal Access Token from the store as follows:

```
"Download_VSTS_Drop_and_Run_Script.PersonalAccessToken": {
      "type": "securestring",
      "defaultValue": "[[[VSTS-PAT]]"
    },
```

>NB. The portal's ARM template outputs: "[[[VSTS-PAT]]", but the article above shows "[[VSTS-PAT]]".  I have tried both and neither work.

**Comment by gregpakes** [comment]
I have managed to get this working by accessing the key vault directly.  I needed to allow access to the keys from ARM templates.  This is done directly on the key vault.

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-keyvault-parameter

**Comment by grwann** [comment]
Hi Greg!

Does the above comment mean that you are unblocked on this issue?

If not, can you share the error message you are getting?

Thank you,
Grace

**Comment by gregpakes** [comment]
@grwann 

I am unblocked, but I still suspect something is wrong.

There is no error message as such, but it's simply clear that the secret is not pulled from the store when using the documented method.

**Comment by drwill-ms** [comment]
@gregpakes which KeyVault stores the secrets you are trying to reference? There is a lab KeyVault which is primarily there for holding private repo personal access tokens, but the only vault the ARM templates will work with is the user's KeyVault. @grwann is trying to repro.

Also, for your earlier query about the formatting being [[[secretKey]] or [[secretKey]], the former is the correct format. We'll get the documentation updated.

**Comment by gregpakes** [comment]
@drwill-ms 

I am accessing the keyvault that devtest lab creates, that has the secrets created by me in the lab.

**Comment by drwill-ms** [comment]
Sorry, I just want to be 100% clear on this. The lab creates 1 + N KeyVaults where 1 is the lab's KeyVault, and N is the number of users that save secrets. Because you say you are using the one that has the secrets created by you in the lab, I assume you mean the one created for you as a user.

**Comment by gregpakes** [comment]
@drwill-ms 

Yes - that would make sense.

I tried to pull our the secret using the "[[[SECRET]]" syntax in the ARM template, but it didn't work.  So i decided to load up the key vaults in Azure.  There were two vaults associated with the lab.  I went through them until I found the one that contained my secret.

I then went into the permissions of that key vault and allowed access to the secrets through ARM.

Then I changed my ARM template to access the keyvault directly with the details here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-keyvault-parameter

**Comment by grwann** [comment]
Hi @gregpakes,

I was trying to repro your case, but I was able to deploy an ARM template using a saved secret through both the Custom Deployment UI, and using the powershell cmdlet New-AzureRmResourceGroupDeployment -ResourceGroupName myrg -TemplateFile mytemplate.json.  I created a Windows VM with the atom artifact, using a saved secret for the vm password and the atom artifact password.

Maybe just to narrow down the issue - could you try deploying an ARM template without artifacts, just the VM, and passing the password as a secret, and seeing if that works?

I am assuming you are deploying your ARM template through a powershell cmdlet?  And how are you generating your ARM template?

**Comment by gregpakes** [comment]
Hi @grwann 

Yes I am deploying through powershell.  Please can you send me your ARM template and i'll compare.

**Comment by gregpakes** [comment]
@grwann I have just tested it through the portal.  It didn't work.  I am trying to use the windows-vsts-download-and-run-script artifact and if I submit the **Personal Access Token** as a secret through the portal, it fails.

The same goes for submission through powershell.  the only way I can get it to work is by manually accessing the secret.

**Comment by grwann** [comment]
@gregpakes here is my template:
https://gist.github.com/grwann/674e8c2c8975c6840f9ce723dc44f8a0

**Comment by gregpakes** [comment]
@grwann Thanks

Can you test with the windows-vsts-download-and-run-script artifact?

I can't get it to work through the portal either.  It only works when I pull the secret from the keyvault manually.

**Comment by grwann** [comment]
Hi @gregpakes 

I was able to deploy a windows vm with the windows-vsts-download-and-run-script artifact - here is my template I used: https://gist.github.com/grwann/506aa565e6f9a0ba8f3594ecf5749d40

**Comment by gregpakes** [comment]
Well this is strange then!

I can literally apply the artifact to an already existing VM (through the azure blade), select the secret from the blade and it fails.  It fails on a 401 error to VSTS.  I am assuming this is because the secret is not being pulled from the store correctly.

Then, I can create an ARM template that accesses the same secret directly through the standard ARM mechanism (directly to the key vault) and it succeeds.  This proves the secret is good. 

confused.....

**Comment by drwill-ms** [comment]
Greg - would you be willing to try the scenario in a new lab? For science.

Also, if you will share your subscription Id, lab name, and rough date/time of a failure I'll look in our logs. You can email me this info at drwill at microsoft.com.

**Comment by gregpakes** [comment]
@drwill-ms 

I actually created a new DevTest lab to test this.  So this is already in a new lab.  But i'm happy to test.

I will email you the details.

**Comment by drwill-ms** [comment]
I'll try it in a lab of my own in the same region you are seeing this as well, if you'll share which region that is.

**Comment by gregpakes** [comment]
@drwill-ms 

West Europe

**Comment by gregpakes** [comment]
Typical - just tested this again and it worked.  I'll assume this was my error.  

Apologies.

**Comment by drwill-ms** [comment]
If it occurs again, just let us know.

**Comment by gregpakes** [comment]
I think I have figured this out.

Secrets created in the lab are local to the user that created them (as far as I know).  I am executing my ARM Templates through VSTS and therefore they are not being executed in the context of my user, therefore the secret does not exist.

Does this make sense?

**Comment by andremarques023** [comment]
@gregpakes did you manage to use windows-vsts-download-and-run-script artifact from the VSTS pipeline? I'm trying to use it inside a ARM Template through the Azure DevTest Labs extension's Create VM task with no success.
