### ISSUE TITLE
Logs from the Artifact Extension are truncated

### ISSUE THREAD

**Issue by gregpakes** [Azure/azure-devtestlab#234]
When I go to the Artifact status blade in the portal, the **Extension Message** seems to be truncated.

It would be really useful to see the full logs here.

I am executing a lengthy powershell script and am trying to output to here, but I only get the last 79 lines of the logs.

**Comment by leovms** [comment]
I created a test artifact where I indicate how many sample log lines to output. I've ran it to output 100 lines. It worked. I then asked it to output 1000 lines and it truncated the output to roughly 4K worth of text.

Can you take a look at your log output, copy it and see if it is roughly 4K worth of text? There may be a 4K limit that we never hit before.

**Comment by gregpakes** [comment]
Hi - I have since changed my powershell script to reduce logging, but I will see if I can do another test.

**Comment by gregpakes** [comment]
I'm not quite sure how you're calculating the 4k number, but my latest one is truncated to 5,369 characters.

**Comment by leovms** [comment]
My test gave me roughly 4K. So, yours is giving you more. I'll have to follow up with the folks from the custom script extension team on this one. Thanks for taking the time to gather more information.

**Comment by leovms** [comment]
I did further investigations and I found that the truncation happens as part of the custom script extension itself. It actually writes only the last chunk of text into its own logs, which we then simply display. Therefore, I will follow up with that team to see if there's resolution to this problem.

**Comment by leovms** [comment]
We have consulted with the CustomScriptExtension team and they have confirmed they only output the last 4K from stdout / stderr. Because of this limitation, outputting entire logs will not be feasible.
