### ISSUE TITLE
Access denied when installing chocolately package

### ISSUE THREAD

**Issue by gregpakes** [Azure/azure-devtestlab#235]
I'm trying to use the chocolately artifact to install the **powershell** chocolately package.

The following logs are found in the event log:

>Windows update  could not be installed because of error 2147942405 "Access is denied." (Command line: ""C:\Windows\System32\wusa.exe" "C:\Users\artifactInstaller\AppData\Local\Temp\chocolatey\PowerShell\5.1.14409.20170510\Win8.1AndW2K12R2-KB3191564-x64.msu" /quiet /norestart /log:"C:\Users\artifactInstaller\AppData\Local\Temp\chocolatey\PowerShell-Install-201705230841.evtx" ")

Looks like a permissions issue.  Are there known issues?

**Comment by leovms** [comment]
None that we're aware. Can you provide more details? What OS, parameters, etc. Anything that could help repro the issue.

**Comment by gregpakes** [comment]
My scenario is that I am trying to get WMF 5.1 onto a 2012 box.

I create a new VM (2012 R2) and I try to apply the chocolately artifact with the package "powershell".  It fails.

**Comment by eosfor** [comment]
Any news on this?

**Comment by leovms** [comment]
We updated the generic `Install Chocolatey Packages` artifact to correct the problem. Please retry and let us know if you're still seeing the issue.

**Comment by Hariarj** [comment]
Hi,

I am also facing issue while installing PowerShell 5.1 using choco; while using Hashi Packer
-- Choco: v0.10.8
-- Windows OS: Windows 2012-R2 DataCenter Edition (Microsoft Azure)
-- choco command 'choco install powershell --version 5.1.14409.20180105 -y'

**Following is the Packer Sequence:**
 "provisioners": [
    {
      "type": "powershell",
      "scripts": [
        "powershell/install-chocolatey.ps1",
        "powershell/install-net452.ps1",
        "powershell/install-powershell51.ps1"
      ]
    }...

**Log**
==> azure-arm: Provisioning with powershell script: powershell/install-powershell51.ps1
    azure-arm: #############################################
    azure-arm: Start: Installing PowerShell 5.1
    azure-arm: Chocolatey v0.10.8
    azure-arm: Installing the following packages:
    azure-arm: powershell
    azure-arm: By installing you accept licenses for the packages.
    azure-arm: Progress: Downloading PowerShell 5.1.14409.20180105... 100%
    azure-arm:
    azure-arm: PowerShell v5.1.14409.20180105 [Approved]
    azure-arm: powershell package files install completed. Performing other installation steps.
    azure-arm: Running on: Windows Server 2012 R2 Datacenter, (ServerDatacenter), Windows Kernel: 6.3.9600
    azure-arm: Installing for OS: Win8.1/2012R2
    azure-arm: Downloading PowerShell 64 bit
    azure-arm:   from 'https://download.microsoft.com/download/6/F/5/6F5FF66C-6775-42B0-86C4-47D41F2DA187/Win8.1AndW2K12R2-KB3191564-x64.msu'
    azure-arm: Progress: 100% - Completed download of C:\Users\packer\AppData\Local\Temp\chocolatey\PowerShell\5.1.14409.20180105\Win8.1AndW2K12R2-KB3191564-x64.msu (18.96 MB).
    azure-arm: Download of Win8.1AndW2K12R2-KB3191564-x64.msu (18.96 MB) completed.
    azure-arm: Hashes match.
    azure-arm: Installing PowerShell...
    azure-arm: Opps we had a error.
    azure-arm: Found the following error(s) and warnings in the MSU log "C:\Users\packer\AppData\Local\Temp\chocolatey\PowerShell-Install-201801090427.evtx"
    azure-arm:
    azure-arm:
    azure-arm:
    azure-arm:
    azure-arm:
    azure-arm:
    azure-arm: ERROR: Running ["C:\Windows\System32\wusa.exe" "C:\Users\packer\AppData\Local\Temp\chocolatey\PowerShell\5.1.14409.20180105\Win8.1AndW2K12R2-KB3191564-x64.msu" /quiet /norestart /log:"C:\Users\packer\AppData\Local\Temp\chocolatey\PowerShell-Install-201801090427.evtx" ] was not successful. Exit code was '5'. See log for possible error messages.
    azure-arm: The install of powershell was NOT successful.
    azure-arm: Error while running 'C:\ProgramData\chocolatey\lib\PowerShell\tools\ChocolateyInstall.ps1'.
    azure-arm:  See log for details.
    azure-arm:
    azure-arm: Chocolatey installed 0/1 packages. 1 packages failed.
    azure-arm:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    azure-arm:
    azure-arm: Failures
    azure-arm:  - powershell (exited 5) - Error while running 'C:\ProgramData\chocolatey\lib\PowerShell\tools\ChocolateyInstall.ps1'.
    azure-arm:  See log for details.
    azure-arm: ##############################################
==> azure-arm:
==> azure-arm: Cleanup requested, deleting resource group ...
==> azure-arm: Resource group has been deleted.
Build 'azure-arm' errored: Script exited with non-zero exit status: 5. Allowed exit codes are: [0]

==> Some builds didn't complete successfully and had errors:
--> azure-arm: Script exited with non-zero exit status: 5. Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.

**Comment by SayreX86** [comment]
I have the same issue, when trying to install powershell 5.1 on EC2 instance with using Packer:
amazon-ebs: ERROR: Running ["C:\Windows\System32\wusa.exe" "C:\Users\Administrator\AppData\Local\Temp\chocolatey\PowerShell\5.1.14409.20180105\Win8.1AndW2K12R2-KB3191564-x64.msu" /quiet /norestart /log:"C:\Users\Administrator\AppData\Local\Temp\chocolatey\PowerShell-Install-201805171205.evtx" ] was not successful. Exit code was '5'. Exit code indicates the following: User (you) cancelled the installation..
amazon-ebs: The install of powershell was NOT successful.

I think, that this issue connected with situation in this post:
https://blogs.technet.microsoft.com/sus/2012/10/30/kb-windows-update-standalone-installer-wusa-returns-0x5-error_access_denied-when-deploying-msu-files-through-winrm-and-windows-remote-shell/

**Comment by alane019** [comment]
I'm having the same issue. Would anyone care to assist?
