### ISSUE TITLE
Duplicated values on help text in Create Custom Image VSTS task.

### ISSUE THREAD

**Issue by andremarques023** [Azure/azure-devtestlab#237]
The help text for both OS State options (Windows and Linux) is incorrect. The values _DeprovisionRequested_ and _SysprepRequested_ appear duplicated.

**Comment by leovms** [comment]
Thank you for reporting it and supplying the fix. I've reviewed the associated PR and merged the changed. Since these changes are minor, we will not push them by themselves. We will do an update once some functionality changes.
