### ISSUE TITLE
Artifact for installing VSTS Build Agent doesn't work

### ISSUE THREAD

**Issue by petehauge** [Azure/azure-devtestlab#244]
There appears to be 2 issues with this artifact
1)  There doesn't appear to be any parameter checking, it's difficult to get the parameters correct.  IE:  we put in the full URL instead of just the account name the first time and took some time to figure it out.  Would be better if the artifact could handle the parameters a bit better
2)  Even with the correct parameters, get an error:  "An error occurred while sending the request" and "Agent configuration failed with exit code: 1".  No real information on why it failed.

**Comment by leovms** [comment]
Artifact has been updated.
