### ISSUE TITLE
Custom Image Name Validation

### ISSUE THREAD

**Issue by gregpakes** [Azure/azure-devtestlab#249]
Has something changed with the custom image name validation when creating a custom image?

I am using the ImageFactory and I am getting an error when running "SnapImageFromVM.ps1".  I now get an error:

> The entity name 'name' is invalid according to its validation rule: ^[^_\W][\w-._]{0,79}(?<![-.])$.

I am also no longer able to create custom images through the portal with spaces, commas and brackets.

Have the validation rules changed?

**Comment by gregpakes** [comment]
I don't seem to be getting this error anymore.  I'll close for now and re-open if the issue continues.

**Comment by gregpakes** [comment]
I am getting this issue again - could it be related to #252?

**Comment by ajay-arora** [comment]
Yes they have changed. These are pretty much the standard validation rules across Azure.
As for spaces, commas, brackets, they were not allowed earlier too, no changes around those.

**Comment by gregpakes** [comment]
@ajay-arora 

> As for spaces, commas, brackets, they were not allowed earlier too, no changes around those.

The image name in the ImageFactory used to contain brackets and spaces, so I'm not sure about this.

I have changed my local copy of SnapImageFromVM.ps1 and removed all the invalid chars, but I'm still getting the error.

I think the issue is the forward slash (/) in the following line in **SnapImageFromVM.json**:

```
"resourceName": "[concat(parameters('existingLabName'), '/', parameters('imageName'))]",
```

I'm not sure how to solve this as the lab name is required.

**Comment by gregpakes** [comment]
Update - The above is wrong.

It seems that the portal allows brackets in it's image names, but the ARM API doesn't.  This is what was confusing me.

**Comment by ajay-arora** [comment]
No, brackets are not allowed in custom image names in the portal as well. Look at the below snapshot while creating a devtestlab custom image.
![snap](https://user-images.githubusercontent.com/12034156/27652661-6825835e-5bf1-11e7-904d-53afe2bdb208.png)

**Comment by gregpakes** [comment]
@ajay-arora 

Ah ok - Might be a US/UK thing but to me that isn't a bracket.

"(" = bracket
"[" = square bracket

**Comment by drwill-ms** [comment]
Ah yes, we call ( a parenthesis.

**Comment by gregpakes** [comment]
So there is still an inconsistency with parentheses between portal and ARM api AFAIK.

**Comment by ajay-arora** [comment]
The parentheses are allowed in both ARM as well as the Portal.
Can you share the exact name where you are seeing the inconsistency ?

**Comment by tanmayeekamath** [comment]
We will be closing this issue. Please reopen if you are still seeing this error.
