### ISSUE TITLE
Security Model is broken!

### ISSUE THREAD

**Issue by tarunaroraonline** [Azure/azure-devtestlab#253]
And yet again the security model in Dev Test Labs is broken. It seems a recent roll out has affected users that have admin permissions to the lab through custom RBAC roles. When the user tries to start a VM that has been auto shut down by policy the following error message shows up... 

`Failed to start virtual machine 'AZSU-D-DTL1-005'. Error: The client 'Tarun.Arora2@xxxcom' with object id '4f95944a-e0e0-4749-b14d-ea759988c730' does not have authorization to perform action 'Microsoft.Compute/virtualMachines/start/action' over scope '/subscriptions/xxx/resourceGroups/azsu-dtlab-devtest-xxxx-001-Dev03-941230/providers/Microsoft.Compute/virtualMachines/AZSU-D-DTL1-005'.`

This is really annoying as this sort of issue has happened in the past and has happened again.

**Comment by drwill-ms** [comment]
Hi Tarun -

DevTest Lab users do not, and never have had, permissions beyond read-only to the underlying compute VM. Based on the resource Id in the error message, it looks like you opened the compute VM and tried to start it. You should open the lab, find the VM listed there, and start it from that blade.

Can you try again from the lab VM list or lab VM blade and let us know if that isn't working for you?

Regards,
David

**Comment by tarunaroraonline** [comment]
@drwill-ms I'll validate this. How about virtual machine resizing then? Suppose I can't do that from the dev test lab blade, this will need to be done from the virtual machine. Doesn't it make it useless, because the VM's are in their own resource group and not in the resource group of the DTL. How do you set up RBAC roles now to deal with the architecture u have in place?

**Comment by drwill-ms** [comment]
DevTest Lab Users do not have the ability to resize their VM. Doing so from the "real" VM would compromise lab VM size policy.

We have a story on the backlog to add that functionality to lab VMs, which would observe lab VM size policy, and I believe we're picking that story up soon.

Until then, the guidance for now would be to create the VM with the size you want. If you find later you need a different size, then you'd need to delete the current VM and create a new one.
