### ISSUE TITLE
Error when deploying nested template using cross resource group deployment

### ISSUE THREAD

**Issue by ChrisLGardner** [Azure/azure-devtestlab#260]
I'm attempting to deploy a template containing a variety of nested templates, one of which is using the new cross resource group deployment option to update resources as part of the deployment. When I deploy manually using PS it completes fine but when attempting to deploy from DevTest Labs I get the following error:

```
Deployment template validation failed: 'The template resource 'UpdateVNetDNS' at line '175' and column '10' is invalid. 
The api-version '2016-09-01' used to deploy the template does not support 'ResourceGroup' property. Please use api-version '2017-05-10' or later to deploy the template. 
Please see https://aka.ms/arm-template/#resources for usage details.'.
```

Is there any way around this?

**Comment by jaymarf** [comment]
Bug fix deployed for this issue and is working its way through our production pipeline.
