### ISSUE TITLE
Constraint of number of VMs per dev test lab user getting bypassed when using template from template repository

### ISSUE THREAD

**Issue by maniSbindra** [Azure/azure-devtestlab#261]
Hi, I am facing the following issue :

I created Devtest Lab with a template repository following the steps mentioned in  https://github.com/maniSbindra/univ-devtest-lab . I modified the parameter file to allow only **one vm per devtest lab user**. Currently only one environment template exists in the template repository which creates a single Ubuntu VM once provisioned. 

After the devtest lab was created I gave access to an user with role devtestlabuser.

The issue is that using the portal from dev test lab the user is able to add multiple environments using the template from the template repository , and a VM is created each time, and **this bypasses the constraint of only one VM per devtestlab user**.

Please let me know if further clarification is needed regarding the issue.

**Comment by leovms** [comment]
Thank you for reporting this, we'll look into it and get back to you.
