### ISSUE TITLE
ConfigMgr - Deployment Issues

### ISSUE THREAD

**Issue by ykhalifa2** [Azure/azure-devtestlab#266]
Hello,

I need to simulate applications deployments with devtestlabs COnfigMgr Scenario to validate my package/Applications.
But the content can't be deployed to the client computer (on the same Vnet with NSG (Allow All Any=Any)

Do you have the same issue?

Thanks,

Yoann

**Comment by ajay-arora** [comment]
Hi Yoann

I didnt understand your question at all. Is this related to Azure DevTest Labs service : https://azure.microsoft.com/en-us/services/devtest-lab/
If yes, can you please explain what you are doing in detail.

**Comment by ykhalifa2** [comment]
Hi,

I have troubleshooted my issue and it came from Artefact "Create new Domain".
Now, the issue is resolved.

Thanks for your help, 

Yoann
