### ISSUE TITLE
How to add Availability set to VM in DevTest lab

### ISSUE THREAD

**Issue by ptoluganti** [Azure/azure-devtestlab#274]
How to add Availability set to VM in DevTest lab?

**Comment by leovms** [comment]
Availability sets are automatically managed by DTL. Can you elaborate on your scenario so we can better guide you? Perhaps, the case you're trying to cover has already been tackled in a different way.

**Comment by ptoluganti** [comment]
Hi thank you for helping.

I am creating build agents in devtest labs and want to assign build agents to different agent pools. Each agent pool will have one availability set that will be set to vm.

**Comment by leovms** [comment]
As previously mentioned, DTL manages the availability sets. The allocation is based on the rules for availability sets. So, one way you can try to get DTL to allocate each agent pool to a different availability set is to create the agent host VM with different sizes (e.g. Standard_D1_v2 VMs will not be added to the same availability set as Standard_A7 VMs).

**Comment by ptoluganti** [comment]
All the Agent VM are of same size in my case. if there is no way to assign availability set to DTL VM.  i am thinking, if once the VM is created, delete the just vm object and keep disk and nic, again create vm with availability set and use the same OS disk and nic. will this be issue with DTL managed availability sets

**Comment by leovms** [comment]
I believe we may be making it more complicated than it may need to be. From what you describe, it makes me think you're using Shared IP, rather than Public IP, in the Advanced options of the Create Lab VM blade (or equivalent in ARM template). If you use Public IPs for the Lab VMs, instead of Shared IPs, you will not be associated to any availability set. Shared IP addresses leverage a load balancer under the covers, which requires an availability set. So, before you try what you propose, can you check if you can instead use a Public IP address?

**Comment by ptoluganti** [comment]
I am using private IP address from an existing subnet. These agents will be domain joined. In my case i might have up to 100 agents, there is a limit of 60 for public IP addresses in azure subscription. yes we can raise request to increase quota but i am thinking it would nice if i could set availability set at the time of VM creation in DTL.

**Comment by leovms** [comment]
I understand. The challenge is that one can only add a virtual machine to an availability set during the creation process. DTL doesn't provide a means for you to specify that option. What I provided before were possible ways to get around it.

Perhaps you should consider using your own ARM templates to do this. Please refer to the tutorial [Create multi-VM environments and PaaS resources with Azure Resource Manager templates](https://docs.microsoft.com/en-us/azure/devtest-lab/devtest-lab-create-environment-from-arm). Let me know if this is even an option. If not, then I'm afraid you may not be able to do what you want.
