### ISSUE TITLE
CopyVHDFromVMToLab.ps1 stops the source VM

### ISSUE THREAD

**Issue by Mike-Honey** [Azure/azure-devtestlab#279]
The script CopyVHDFromVMToLab.ps1 stops the source VM.  This should be stated clearly in the comments around the initial parameters.

**Comment by tanmayeekamath** [comment]
Thanks for the feedback. We will update the script accordingly.

**Comment by tanmayeekamath** [comment]
We will be closing this issue. Please reopen if you are still seeing this error.
