### ISSUE TITLE
CopyVHDFromVMToLab.ps1 throws "The specified container does not exist" on Copying VHD

### ISSUE THREAD

**Issue by Mike-Honey** [Azure/azure-devtestlab#280]
I'm trying to run the CopyVHDFromVMToLab.ps1 script.  It gets up to the step "Copying VHD x to y".  Then it throws:

ERROR: The remote server returned an error: (404) Not Found. HTTP Status Code: 404 - HTTP Error Message: The specified container does not exist.

I'm unclear what to put for $VHDFileName - should it be the existing VHD's Name? The existing VHD URI? Something else?

I also see an earlier line always returns a blank - that looks to me like a coding bug (no other mention of "Instance"), or is it important?

**Comment by guestsalt** [comment]
I had this error, the script is attempting to use a container called 'uploads'. I noticed after the first failure there were no containers at all let alone an uploads one, but on checking a few minutes later the uploads container was there and the script ran fine when I kicked it off again with parameters unchanged.

**Comment by tanmayeekamath** [comment]
We will be closing this issue. Please reopen if you are still seeing this error.
