### ISSUE TITLE
CopyVHDFromVMToLab.ps1 - please replace with portal UI

### ISSUE THREAD

**Issue by Mike-Honey** [Azure/azure-devtestlab#281]
I'm wasting a lot of time hacking around in PS with the lengthy CopyVHDFromVMToLab.ps1 script and not achieving anything.  

Surely copying an existing VM into DevTest Labs is an everyday requirement - please built it into the portal UI.  I couldn't recommend DevTest Labs to anyone if this is the "Getting Started" experience.

**Comment by tanmayeekamath** [comment]
Hi Mike 
Thank you for feedback.
I will add this to our backlog and get back to you once I have an update on the timeline for it.

-Tanmayee Kamath
  Program Manager
  Azure DevTest Labs

**Comment by smrau** [comment]
It's been a year, and no progress? As Mike says, this is such an obvious feature that is missing from the portal, particularly as we move towards Lab Services.

**Comment by tanmayeekamath** [comment]
The scripts have been re-written since. Please reopen if you are still seeing this error.

**Comment by smrau** [comment]
Thanks for the announcement, even if it is more than six months too late. I wrote my own bash scripts to copy my custom image and spin up a bunch of VMs and shut them down. 

My honest opinion is that you guys are not up to the job. Please ask Microsoft to replace you with people who know what they are doing. Why the f**k should I have to write my own custom code to do something your product should do for me??
