### ISSUE TITLE
issue with chocolatey artifact

### ISSUE THREAD

**Issue by Andy-bridle** [Azure/azure-devtestlab#286]
Hi, 
I'm hitting an issue that I think is caused by the new installer script in the chocolatey artifact.
I'm currently working round the issue by ensuring I only use this artifact once in each of my VM templates and that it is not preceeded by any other artifacts that also use chocolatey. 

I started seeing the issue around the time of the below commit:
https://github.com/Azure/azure-devtestlab/commit/461b75d3587b59382db81b9f1cac85d6b2b5892c

If I create a deployment (ARM template or portal) that includes this artifact after another artifact that has used chocolatey then this one always fails with the below:

I can recreate simply in portal (create a vm, add 2 copies of this artifact with different packages, the 2nd fails)

Validating parameters.
Configuring PowerShell session.
Ensuring latest Chocolatey version is installed.
WARNING: It's very likely you will need to close and reopen your shell
before you can use choco.
WARNING: You can safely ignore errors related to missing log files when
upgrading from a version of Chocolatey less than 0.9.9.
'Batch file could not be found' is also safe to ignore.
'The system cannot find the file specified' - also safe.
WARNING: Not setting tab completion: Current user is SYSTEM user.

ERROR: Cannot find path 'C:\ProgramData\chocolatey\choco.exe.old' because it does not exist.

The artifact failed to apply.

**Comment by leovms** [comment]
Thank you Andy, for reporting this. We'll take a look and work on resolution.

A workaround is to specify multiple packages in a single instance of this artifact. Just separate each by a comma, space or semi-colon.

**Comment by RobertKomara** [comment]
Hi there, what if you are installing artifacts with flag options such as: `microsoft-r-open --version 3.4.2`
and `r.studio` at the same time?

Thanks!

**Comment by snarfblatt** [comment]
This happens for me as well. Is there any resolution to it?

**Comment by leovms** [comment]
Artifact has been corrected. Please try it again. Let us know if it doesn't work for you.
