### ISSUE TITLE
Encoding Issues on CopyVHDFromVMToLab.ps1

### ISSUE THREAD

**Issue by akalcik** [Azure/azure-devtestlab#289]
There must be some encoding issues with the [CopyVHDFromVMToLab](https://github.com/Azure/azure-devtestlab/blob/master/Scripts/CopyVHDFromVMToLab.ps1) as I wasn't able to run this script on my Windows machine. When I run the script I get the error message:

```
+ }
+ ~
Unexpected token '}' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
```

Now when I open the script in the PowerShell ISE there are some encoding issues which leads to error before.

Line 192
```powershell
$destContext = New-AzureStorageContext â€“StorageAccountName $CopyContext.LabStorageAccountName -StorageAccountKey $CopyContext.LabStorageAccountKey
```

Line 200
```powershell
$srcContext = New-AzureStorageContext â€“StorageAccountName $CopyContext.VMStorageAccountName -StorageAccountKey $CopyContext.VMStorageAccountKey
```

When I replace the ```â€``` with ```-``` it corrects the parsing issue.

**Comment by leovms** [comment]
Thank you. I have gone ahead and made the corrections.
