### ISSUE TITLE
The artifact authoring experience is terrible.

### ISSUE THREAD

**Issue by mithunshanbhag** [Azure/azure-devtestlab#34]
I've spent quite a bit of time authoring Azure RM templates, VSO build tasks and DevTest Lab artifacts. When I compare and contrast the experiences, the DTL artifact authoring is the worst of the three. Here is some (hopefully actionable) feedback:

## Artifact manifest

**Support more parameter types:** Looks like we only support string and securestring types for parameters. Can we please add support for other types (int, bool, object, array etc)?

**Support static dropdown lists for parameters:** Self explanatory.

**Support dynamic dropdown lists for parameters:** Similar to  VSO tasks, we should provide dynamic dropdown lists for parameters. VSO dynamic dropdowns allow you to call REST endpoints and bind the result to the underlying list. This functionality would be tremendously useful for DevTest Lab artifacts (E.g. You can query the Chocolatey/WebPI catalog and populate your dropdown with list of available packages, versions, skus etc). See example of a VSO dynamic dropdown [here](https://github.com/Microsoft/vso-agent-tasks/blob/fa43e58d00d6d8f1f1482578c935bf901f774049/Tasks/AzureCloudPowerShellDeployment/task.json#L142).

**Support regex or custom validators for string parameters:** Currently, when using string parameters we can only avail of "allowEmpty" and "defaultValue" fields. Would be great if we can specify regex and other custom validators (e.g. string length must meet some conditions etc) in the artifactfile.json.

**Built-in helper functions:** Similar to Azure RM template functions ([here](https://azure.microsoft.com/en-us/documentation/articles/resource-group-template-functions/)) we should provide some built-in helper functions that could be used in artifactfile.json (e.g. function to url-encode a string, find-replace a substring etc).

## Artifact scripting

**Powershell named parameters:** It is not possible to call named parameters in a powershell script, if the parameter values (usually supplied by the lab user) contains a quote or a whitespace.

**Running as elevated admin:** Artifact authors should not have to write code to run their artifacts in the context of an elevated admin (this is what most chocolatey based artifacts are doing. [See example here](https://github.com/Azure/azure-devtestlab/blob/master/Artifacts/windows-clone-git-repo/StartChocolatey.ps1)). Would be great if the artifactfile.json exposed some field (say 'RunElevated'), which when used, causes the artifact to automatically run elevated.

## Artifact execution

**Indicating "critical" errors:** As of today, artifact execution errors are treated as non-critical. If one artifact fails, it does not stop execution of other artifacts in the list. Artifact authors (and/or lab users) need a mechanism to mark an artifact failure "Critical". E.g. If installation of VS or SQL fails, then don't bother installing the other artifacts in the list (abort execution of all subsequent artifacts). This is tremendously useful for long-running machine prep scenarios (e.g. dev machine prep involves installation of VS, cloning repos, installing editors & other tools etc).

**Reboot after execution:** Some installers exit with 3010 code, which indicates a successful installation, but a reboot is required. There should be a field (say 'RebootIfSuccessful'), which when used, forces the machine to reboot after the artifact executes.

## Checkin process(es)

**Bot/Auto validation on checkins and submitted PRs:** We should auto-validate all PRs and checkin to the artifact repo master (license agreement check, schema checks for artifactfile.json, running unit tests etc). This is standard practice for many azure repos (E.g. The Azure quickstart gallery runs a travis/jenkins bot on every PR and checkin. See example [here](https://github.com/Azure/azure-quickstart-templates/pull/850)). I accidentally checked in a regression (wrong casing for artifactfile.json). Issues like these are hard to diagnose and should be caught by the auto-validation process.

**Need mandatory readme.md for artifacts:** All artifacts should have a mandatory readme.md ([see example here](https://github.com/Azure/azure-devtestlab/tree/master/Artifacts/windows-clone-git-repo)). On the portal's 'Add artifact' blade, it would be useful to have a hyperlink to the artifact’s readme file. E.g. http://imgur.com/lt3f5pX

## Miscellaneous

**Documentation:** Where does the most up to date documentation on artifact authoring reside? [On MSDN?](https://azure.microsoft.com/en-us/documentation/articles/devtest-lab-artifact-author/) Or [on github](https://github.com/Azure/azure-devtestlab/tree/master/Documentation)? Both these set of docs seem to be a bit out of sync.

**Custom log files:** What is the "recommended" location for generating custom log files (via the artifact's powershell script)? I currently log to this location: %SystemDrive%\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\[version]\Downloads.

**Comment by gxy001** [comment]
Thanks for reporting the issues. Some of them are feature requests. Would you mind creating tickets at our UserVoice forum (where we collect votes from the community on feature requests)? 

[https://feedback.azure.com/forums/320373-azure-devtest-labs](https://feedback.azure.com/forums/320373-azure-devtest-labs)

Thanks,
Xiaoying Guo
Senior Program Manager, Azure DevTest Labs

**Comment by leovms** [comment]
Anything actionable has been updated in the backlog.

**Comment by yashg7cr** [comment]
I created custom artifact and uploaded in git hub public repository ,given git hub credentials in azure configuration policies.The application which i want to apply artifact on azure virtual machine is uploaded from my own organization HTTP server,here the scenario is artifact.json file and powershell.ps1 file and application which i want to install is downloading from my organization server.Upto here the file and required downloads are downloading correctly,while execution to install application its starts the application but the application is not installed,when i saw in task manager, application status showing running but process % is 0.Later when i saw on azure artifact details its showing succeded.Kindly help me from this issue.

**Comment by joerage** [comment]
Hi yashg7cr,

please open a new issue and share your script and the logs you get.

Thanks,
Jonathan
