### ISSUE TITLE
Join Active Directory (AD) domain

### ISSUE THREAD

**Issue by danmyhre** [Azure/azure-devtestlab#347]
Anyone else having the "Join Active Directory (AD) domain" artifact run for 1-2 hours and then timeout?

**Comment by leovms** [comment]
We've not seen other reports of this issue. Can you please retry and confirm if you still have the same issue?

**Comment by danmyhre** [comment]
Seems to be an issue with sysprep'd images.

**Comment by leovms** [comment]
If you run with a small size VM, the process of updating the Custom Script Extension can be lengthy. They have added throttling where they limit their CPU usage. If you try with a larger size VM, once it completes the CSE upgrade process, you can resize the VM to use a smaller size.

**Comment by danmyhre** [comment]
I was trying with A3, which should be big enough to support this.  I re-tested today and now it is working with VMs down to A2 which is good.  I think there may have been a service issue going on last week as things were running slower than normal.  Thank you!
