### ISSUE TITLE
Deploying a new lab fails in Azure Portal

### ISSUE THREAD

**Issue by SirEel** [Azure/azure-devtestlab#351]
My first two attempts to create Azure DevTest Labs in the portal both failed. I see the labs listed in my resources, but their status is "Deployment Failed". I see nothing telling me why.

I cannot delete the labs either. I get error saying their not "ready" to be deleted. They are zombies.

The entire ADTL feature appears broken. Can someone explain why?

Richard

**Comment by SirEel** [comment]
I tried a third time and the lab was created. I still don't know why the first two attempts failed. I could find now useful log information.

I was, however, able to delete the first two "failed" labs. Apparently that just needed more time.

It's unclear to me what it means to say a lab has been "created" but that its "deployment" has failed.

**Comment by drwill-ms** [comment]
SirEel, we had an incident lasting 2.5 hours this morning that might have impacted you. See details here: https://blogs.msdn.microsoft.com/devtestlab/2018/02/16/users-may-have-experienced-issues-while-trying-to-perform-vm-operations-in-labs/.

Are you able to delete the failed lab now?
