### ISSUE TITLE
ARM Deployment Fails Due to Resource Locks

### ISSUE THREAD

**Issue by RickFlist** [Azure/azure-devtestlab#357]
Hello,

I am attempting to deploy https://github.com/Azure/azure-devtestlab/tree/master/Samples/101-dtl-create-lab. However the deployment is failing because when deleting the Storage Account and Key Vault that are deployed because of resource locks.

While the deployment is hung, I can go and delete the resource locks and the deployment will complete successfully

What's going on here? The template doesn't even call for a Key Vault. Also, two SAs are created as part of the deployment - the one I specify below and then some temporary one that is then later deleted.

`DTL Template`
`{                                                                                                    `
`  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",       `
`  "contentVersion": "1.0.0.0",                                                                       `
`  "parameters": {                                                                                    `
`    "LabName": {                                                                                     `
`      "type": "string",                                                                              `
`      "metadata": {                                                                                  `
`        "description": "The name of the new lab instance to be created"                              `
`      }                                                                                              `
`    }                                                                                                `
`  },                                                                                                 `
`  "variables": {                                                                                     `
`    "labNameRoot": "[concat('Dtl-',parameters('LabName'))]",                                         `
`    "labVnetName": "[concat(variables('labNameRoot'),'-VirtualNetwork')]",                           `
`    "labVnetPrefix": "10.0.0.0/16",                                                                  `
`    "labVnetSubnet01Name": "Subnet-01",                                                              `
`    "lavVnetSubnet01Prefix": "10.0.0.0/24",                                                          `
`    "storageAccountName": "[toLower(replace(concat(variables('labNameRoot'),'-SA'),'-',''))]",       `
`    "storageAccountType": "Standard_LRS",                                                            `
`    "keyVaultName": "[concat(variables('labNameRoot'),'-KeyVault')]"                                 `
`  },                                                                                                 `
`  "resources": [                                                                                     `
`    {                                                                                                `
`      "apiVersion": "2017-04-26-preview",                                                            `
`      "type": "Microsoft.DevTestLab/labs",                                                           `
`      "name": "[variables('labNameRoot')]",                                                          `
`      "location": "[resourceGroup().location]",                                                      `
`      "resources": [                                                                                 `
`        {                                                                                            `
`          "apiVersion": "2015-06-15",                                                                `
`          "type": "Microsoft.Network/virtualNetworks",                                               `
`          "name": "[variables('labVnetName')]",                                                      `
`          "location": "[resourceGroup().location]",                                                  `
`          "properties": {                                                                            `
`            "addressSpace": {                                                                        `
`              "addressPrefixes": [                                                                   `
`                "[variables('labVnetPrefix')]"                                                       `
`              ]                                                                                      `
`            },                                                                                       `
`            "subnets": [                                                                             `
`              {                                                                                      `
`                "name": "[variables('labVnetSubnet01Name')]",                                        `
`                "properties": {                                                                      `
`                  "addressPrefix": "[variables('lavVnetSubnet01Prefix')]"                            `
`                }                                                                                    `
`              }                                                                                      `
`            ]                                                                                        `
`          },                                                                                         `
`          "dependsOn": [                                                                             `
`            "[resourceId('Microsoft.DevTestLab/labs', variables('labNameRoot'))]"                    `
`          ]                                                                                          `
`        },                                                                                           `
`        {                                                                                            `
`          "type": "Microsoft.Storage/storageAccounts",                                               `
`          "name": "[variables('storageAccountName')]",                                               `
`          "apiVersion": "2016-01-01",                                                                `
`          "location": "[resourceGroup().location]",                                                  `
`          "sku": {                                                                                   `
`            "name": "[variables('storageAccountType')]"                                              `
`          },                                                                                         `
`          "kind": "Storage",                                                                         `
`          "properties": {},                                                                          `
`          "dependsOn": [                                                                             `
`            "[resourceId('Microsoft.DevTestLab/labs', variables('labNameRoot'))]"                    `
`          ]                                                                                          `
`        }                                                                                            `
`      ]                                                                                              `
`    }                                                                                                `
`  ]                                                                                                  `
`}                                                                                                    `

**Comment by RickFlist** [comment]
I just went back to muck with the DTL, and I am getting the message "Corrupted: cannot find lab storage account 'adtltoddletest041298'" 

That's the storage account that is deleted as part of the deployment

**Comment by RickFlist** [comment]
Just tried the deployment again using the unmodified template at https://github.com/Azure/azure-devtestlab/tree/master/Samples/101-dtl-create-lab and the deployment stalls for the same reason with message `The scope '/subscriptions/[Redacted]/resourcegroups/[Redacted]/providers/Microsoft.Storage/storageAccounts/[Redacted]' cannot perform delete operation because following scope(s) are locked: '/subscriptions/[Redacted]/resourcegroups/[Redacted]/providers/Microsoft.Storage/storageAccounts/[Redacted]'. Please remove the lock and try again.`

**Comment by RickFlist** [comment]
Looks like this is a bug when deploying with the Complete value for the -DeploymentMode parameter in AzureRM PowerShell. If you set it to complete, the deployment will stall. If you set it to Incremental, it will deploy.

**Comment by drwill-ms** [comment]
Hi Rick -

Lab creates several other Azure resources it will need to service requests, including a storage account, a KeyVault, and (usually) a vnet. You won't see those resources spelled out in the ARM template. The lab will create them. (VNet is handled a bit differently, but the concept is the same.)

Because customers have often deleted these required resources, the lab puts resource locks on them. That prevents accidental deletion. It also makes lab's resource group deletion fail due to locked resources being inside it. If someone cares to delete the locks and bypass this, it is easy to do.

You are right that you found the DeploymentMode parameter as the culprit here in tripping up your ARM deployment, but it is not a bug. Combined with the other info I gave above, that explains the error you were seeing.

Regards,
David

**Comment by RickFlist** [comment]
Thanks David! 

Is there a way I can control the naming convention applied to the auto-created assets? It's fine if they are required and whatnot, but I have a very strict naming convention that is used for various automagic purposes, and having a couple assets that don't follow the naming convention causes a bit of a headache.

**Comment by RickFlist** [comment]
RE: Not a bug - While it may not be a bug there is still room for improvement here - for example some verbiage on the page hosting the template informing the user of the known issue or having some logic added to the Complete deployment model - either always pave over regardless of locks or add a flag that will force overwrite of locked resources.

**Comment by RickFlist** [comment]
For example, because of the extremely poor error messaging, it wasn't clear what was happening. I didn't realize that the resources were auto-created and had no idea that a lock was the root cause until I spent 3 hours cussing loudly at Azure for being so goddamned obtuse. To date, that has happened 0 times in AWS because their documentation is bulletproof.

**Comment by drwill-ms** [comment]
Rick -

The names of the required resources are based on the lab name, but changed to 1) conform to restrictions those resources have on names and 2) to ensure uniqueness. DTL does not offer a way to specify the names.

Can you elaborate more for me on how your naming convention works for you?

You have a fair point about the documentation. Although I didn't expect the error due to the confluence of factors, once I saw the error you got it made sense to me. I'll look for a good place in the docs to indicate one should use -DeploymentMode Incremental.

**Comment by drwill-ms** [comment]
Updated https://github.com/Azure/azure-devtestlab/blob/master/Samples/101-dtl-create-lab/README.md.

**Comment by RickFlist** [comment]
Sure. I will be using segmented names (e.g. WST-US1-KV-01, for example) as a naming convention. Each "piece" of the naming convention means something. So for example, with VMs, if I wanted all odd nodes (for say an A/B deployment) then I will get a list of VMs, split on the dash, and if the number is divisible by two, it's in set B. Another example would be servers by role, e.g. I want all APP servers so I grab all VMs with APP in the name. Azure does have some robust ways to query for things but they don't (can't?) account for every single scenario.

It also helps because it's easier to remember how to filter on a name than it is to remember some of the somewhat arcane search syntax required by some of the cmdlets. Yes I know devs shouldn't be that lazy but I guarantee Ops folks are so harried they will take the easiest path every time.

**Comment by RickFlist** [comment]
Where might I submit a feature request to allow for naming of auto-created assets?

**Comment by drwill-ms** [comment]
One thing to consider is that storage account names are extremely limited. You are not allowed upper case characters, dashes and other special characters, spaces, etc.

I'll pass on your request to our PM team. We have heard it before from a few customers, but the feature priority has been low.

Have you considered using resource tags? You can use a more high-fidelity approach to classifying your resources.

**Comment by RickFlist** [comment]
So I typed up a few responses and I think the best way to put it is this way:
It's a label right? You only get as much value out of the label as you have control in creating it. For example, by forcing suffixes, I cannot search for all storage accounts that end in "sa" because I can't force all storage accounts to end in "sa". If I labeled my storage accounts with a suffix to indicate it's purpose, that methodology is broken because I have no control over the names of assets created for DTL. 

We do use tags; it's pretty much the only way we can universally guarantee knowing some things, like the date a resource was deployed. We can develop processes around this, but why should we when I can just bake most of the metadata about an object into it's label?

And keep in mind there are two distinct user bases here - developers and operations guys. The former generally work to achieve a specific goal while the latter are generally trying to stop the house from burning down.

**Comment by drwill-ms** [comment]
I hear you Rick, and I appreciate your sharing additional perspective. I will share this with the PM team.

**Comment by RickFlist** [comment]
Danke

**Comment by SethuSP** [comment]
Is there any way i can change the storage account property like to allow supportsHttpsTrafficOnly for the storage account that is automatically created with the DTL?
We have polices written tenant level to block storage account creation with supportsHttpsTrafficOnly disabled and hence the DTL creation deployment fails with DTL in failed state.
