### ISSUE TITLE
ARM Deployment fails - where are the logs ?

### ISSUE THREAD

**Issue by johnkattenhorn** [Azure/azure-devtestlab#358]
We are trying to use DevTestLab to deploy one of our ARM templates but is fails.

The only error we can find is `New-AzureRmResource : The operation failed because resource is in the: 'Failed' state. Please check the logs for more
details.` 

But can't find the logs - where's the best place to look to find out what the problem is ? 

The ARM works fine outside of DevTestLab

**Comment by leovms** [comment]
You can use the same viewer as when deploying the ARM outside of DTL. However, the location will be within the context of the resource group used by DTL.

**Comment by 4c74356b41** [comment]
@leovms well, this is not true. maybe if the deployment starts that holds. but if the deployment doesnt start I dont see any errors in the log. only see some dtl events.
