### ISSUE TITLE
Add artifact for NVM installation on Linux

### ISSUE THREAD

**Issue by ross-bohr** [Azure/azure-devtestlab#362]
Node Version Manager (NVM) is a popular facility for managing Node.js (and NPM) versions on a target machine. Azure DevTest Lab artifact for NVM installation on Linux is very useful. I suggest we add it to the list. I am willing to implement it.

**Comment by ross-bohr** [comment]
@leovms , kindly review the above idea.

**Comment by leovms** [comment]
Done. Thank you for the contribution.
