### ISSUE TITLE
Debugging linux artifacts is unecessarily difficult

### ISSUE THREAD

**Issue by samedder** [Azure/azure-devtestlab#370]
Just wanted to provide feedback about difficulties I've had debugging Linux artifacts:

- No documentation on where log files are stored
- Stdout log files seem to be deleted for artifacts that are deployed successfully
- Portal does not render newline terminated output so it becomes very difficult to read error logs from the portal

**Comment by tanmayeekamath** [comment]
Hi @samedder ,
Thanks for sending the feedback. 
I have made a note of these in our backlog and we will aim at fixing them as soon as we can.

**Comment by samedder** [comment]
@tanmayeekamath were any improvements made in this area?

**Comment by tanmayeekamath** [comment]
@samedder, we are currently working on moving to a newer technology to run artifacts on VMs. This should significantly resolve existing customer pain points w.r.t artifacts. We have made a note of your issues as well and are making sure they get addressed as a part of our upgrade. Hope this helps!
