### ISSUE TITLE
azure.parameter.json not picked

### ISSUE THREAD

**Issue by jeevanGit** [Azure/azure-devtestlab#371]
When I am generating a template, there are two files that I am using, azuredeploy.json and azuredeploy.parameter.json. As per the documentation, if azuredeploy.parameter.json is present, the value from azuredeploy.parameter.json will be picked. However in devlabs, this is not happening. This works as expected on custom deployment.

**Comment by drwill-ms** [comment]
Jeevan -

How are you using the ARM templates? What is being deployed inside?

I am assuming you are using the BYOA (bring your own ARM) feature where you put ARM templates in a Git repo, configure it with the lab, and have lab deploy the ARM template like you would deploy a lab VM. Is that right?

If so, are you using the Azure Portal to deploy the ARM template?

Regards,
David

**Comment by jeevanGit** [comment]
Thanks a lot David, appreciate your quick response.

**Comment by leovms** [comment]
Jeevan, as a workaround, you can add default values in the `azuredeploy.json` parameters and they will get picked up.

**Comment by jeevanGit** [comment]
@leovms 

Thanks, we have already done that. We have created a tool which will automate this and make some intelligent assumptions. I will check this into git repo and will update the link here.

**Comment by jeevanGit** [comment]
The only problem with this approach is that, it makes me deviate from the inherent design of keeping the template constant and abstracting out the variants into parameter file. However, it is not a deal breaker at the moment. Just need to deal with bloated `azuredeploy.json`. The reason for the tool is that when we deal with complicated infrastructure like `kubernetes`, it takes lot of repetitive effort and it also introduces errors which is difficult to troubleshoot.

**Comment by jeevanGit** [comment]
@leovms / @drwill-ms 
I think the most important and immediate thing will be to update the documentation. The documentation is completely misleading in this regard. Can someone raise a pull request for this ?

**Comment by tanmayeekamath** [comment]
Hi Jeevan,
Thanks for the feedback and the clarification on your scenario.
As a work around you can include these parameters as defaults in the ARM template itself. 
Currently, we don't support reading from a parameters.json  file. I have added this feature request to the backlog and I will update you once we have a timeline for it. 
Please feel free to add this ask on our [user voice](https://feedback.azure.com/forums/320373-devtest-labs) to allow more people to vote for it as well. 
Thanks,
Tanmayee

**Comment by ChrisLGardner** [comment]
Is there a workaround for when your parameters.json file is pulling values from a central Key Vault? I obviously can't put these into default values and DTL seems to use a random GUID each time it tries to access the Key Vault. 

I've seen a feedback/uservoice post about creating a DTL service principle to grant permissions to but I'm surprised it doesn't respect the "All access for template deployment" access control unless it's just due to the way you're doing the deployment and how Key Vault expects the request to come in, i.e. via the parameter.json part of the template.

**Comment by tanmayeekamath** [comment]
We do have a feature in our backlog to implement team secrets.

**Comment by jackchenquest** [comment]
OK Looks like DevTest Labs still doesn't pickup azuredeploy.parameters.json value today (2021 now), and the document https://docs.microsoft.com/en-us/azure/devtest-labs/devtest-lab-create-environment-from-arm still claim it does, and there is also inconsistent filename in the document :
azuredeploy.parameter.json
azuredeploy.parameters.json 

So users have to try both and confirm neither worked.

This is disappointing.

**Comment by shrziaie** [comment]
@tanmayeekamath , @jackchenquest  
I had a similar issue with adding new custom Azuredeploy parameters (custom.azuredeploy.parameters.json) and the parameter's value didn't pick after deploying by Visual Studio. I was able to fix the issue with simple changes.
1. Open the Visual Studio project file in notepad editor.
2. Look into the xml elements for the "custom.azuredeploy.parameters.json".
3. Change it from None to Content.
While the xml element is None the MS Build will not compile the file then the value of the parameter will not deploy.

Sample wrong Xml element :
```
<ItemGroup>
	<Content Include="azuredeploy.json"/>
	<Content Include="azuredeploy.parameters.json"/>
	<Content Include="Deploy-AzureResourceGroup.ps1"/>
	<None Include="Deployment.targets">
		<Visible>False</Visible>
	</None>
	**<None Include="custom.azuredeploy.parameters.json"/>**
</ItemGroup>
<Target Name="GetReferenceAssemblyPaths"/>
</Project>
```

Sample correct Xml element:
```
<ItemGroup>
	<Content Include="azuredeploy.json"/>
	<Content Include="azuredeploy.parameters.json"/>
	<Content Include="Deploy-AzureResourceGroup.ps1"/>
	<None Include="Deployment.targets">
		<Visible>False</Visible>
	</None>
	**<Content Include="custom.azuredeploy.parameters.json"/>**
</ItemGroup>
<Target Name="GetReferenceAssemblyPaths"/>
</Project>
```
