### ISSUE TITLE
BYOT no longer deploying due to not finding vnet in DTL

### ISSUE THREAD

**Issue by ChrisLGardner** [Azure/azure-devtestlab#373]
I have a template that has previously worked when deploying from DTL, it's sitting in a git repository in VSTS. The template spins up a few VMs and joins them to a VNet that I specify at deployment time but which isn't in the DTL resource group. I'm now seeing the following error:

`The Resource 'Microsoft.Network/virtualNetworks/DTL-Name' under resource group 'DTL-PreviewRG632835' was not found.`

There isn't a VNet called that in the resource group and I'm not trying to join the VMs to it even if it did exist. I can't find any reference in my template to that VNet so I'm assuming it's something DTL is doing as part of it's template validation or provisioning.

Are there any details on this and how to deal with it?

**Comment by mmydland** [comment]
Hi Chris, I am sorry that you are having this issue.  I took a look in our telemetry, but unfortunately could not find any information. Could you share your environment name and subscription ID with me directly at mark.mydland@microsoft.com so that I can dig a little deeper?

**Comment by tanmayeekamath** [comment]
We are closing this issue here. Please reopen if you are still seeing this error.
