### ISSUE TITLE
Url to download agent is null

### ISSUE THREAD

**Issue by MatchingRadar** [Azure/azure-devtestlab#374]
I am getting this following error when running my VM with an asset VSTS Build Agent - Not 100% sure if Artifacts/windows-vsts-build-agent/vsts-agent-install.ps1 is the correct file but looks like it might be.... Anyway here is the error:
```
Validating parameters
Preparing agent installation location
I am getting the following error:
Checking for previously configured agent
Downloading agent package
ERROR: Failed to download agent due to Invoke-WebRequest : Cannot validate argument on parameter 'Uri'. The argument 
is null or empty. Provide an argument that is not null or empty, and then try 
the command again.
At C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.9\Downloads\1\
PublicRepo\master\0ec9b514482cd5d0f1531852d8b530edd73f049f\Artifacts\windows-vs
ts-build-agent\scripts\vsts-agent-install.ps1:161 char:36
+             Invoke-WebRequest -Uri $agent.downloadUrl -Headers $heade ...
+                                    ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-WebRequest], ParameterB 
   indingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Power 
   Shell.Commands.InvokeWebRequestCommand
```

I can see this on line 141
`$vstsUser = "AzureDevTestLabs"`
Do i need to add this user to my VSTS?

**Comment by MatchingRadar** [comment]
appears to work on a different server base - i was using Windows Server, version 1709 - switched to Visual Studio Enterprise 2017 (latest release) on Windows Server 2016 (x64) and it works fine. Closing this.

**Comment by slime-uk** [comment]
I'm getting this error on a 1607 Windows Server 2016 VM build.  I need GUI rather than core, so changing version is not an option
