### ISSUE TITLE
Support a shared library

### ISSUE THREAD

**Issue by chcosta** [Azure/azure-devtestlab#375]
Requiring that each artifact be self-contained within the repo prohibits code reuse.  It would be great if a shared library was supported so that we could define a folder which is automatically deployed with the artifact and allows code to be shared between artifacts.

**Comment by tanmayeekamath** [comment]
Thanks for the feedback. We have added this to our backlog. We will update you once we have a timeline for implementation. 
Please post feature requests on our user voice forum here: https://feedback.azure.com/forums/320373-devtest-labs

**Comment by chcosta** [comment]
FYI @riarenas @ChadNedzlek

**Comment by chcosta** [comment]
@tanmayeekamath, what's the update?

**Comment by tanmayeekamath** [comment]
Hi Christopher,
This item continues to be in the backlog. Unfortunately, we have prioritized it yet and are looking at items that are more frequently asked and can solve problems for a larger group of customers. I will update once we have a timeline for this feature. Hope this helps.
