### ISSUE TITLE
Cannot set or update property disallowPublicIpAddress.

### ISSUE THREAD

**Issue by lukka** [Azure/azure-devtestlab#386]
I am experiencing this issue:

   *  Deploy a ARM template with azure cli 2.0 on a Windows machine:

`>az group deployment create --name DeployName --resource-group DevTestLabExperiment --template-file azuredeploy.json  --parameters @azuredeploy.parameters.json
`

    *   The first time it works. If run a second time when the machine is already created and running, this error is generated:

```
Deployment failed. Correlation ID: 31c4137b-b688-49e6-8bea-85b2ddc23714. {
  "error": {
    "code": "CannotSetProperty",
    "message": "Cannot set or update property disallowPublicIpAddress."
  }
}
```

**Comment by tanmayeekamath** [comment]
Apologies for the delay. Was this resolved for you?

**Comment by lukka** [comment]
I need to retry again to confirm this. Did you investigated at all about this?

**Comment by leovms** [comment]
@lukka, the property `disallowPublicIpAddress` can only be set during creation, as it is used to determine the type of IP address to use. This is by design.

**Comment by lukka** [comment]
@leovms i am not changing the value of that property, it is still the same when i created the machine, and the same when I am updating the machine. 

This breaks the deployment of an ARM template when using Incremental mode.

This means customers needs separate template for creating and updating an Azure resource. Hence the separation between template and paramenters (e.g. template.json and template_parameters.json file), that allows to use same template with different data for updating an existing resource, totally unusable.

**Comment by leovms** [comment]
Good point. Let me look at the code and see what we're doing there. Thanks for the feedback.

**Comment by sindstar** [comment]
@lukka - Did you set that property at all in your initial template or did you leave it blank? Also, did you do a GET on the resource before performing the PUT again? You should be unblocked if you did a GET and then a PUT again for updating. We will look into making this experience better as currently sending in a blank is treated as 'false' and if you don't send it in a 'false', it will fail.

**Comment by vinagesh** [comment]
@lukka - Did you set that property at all in your initial template or did you leave it blank? Also, did you do a GET on the resource before performing the PUT again? You should be unblocked if you did a GET and then a PUT again for updating. We will look into making this experience better as currently sending in a blank is treated as 'false' and if you don't send it in a 'false', it will fail.

**Comment by lukka** [comment]
it is set to false in the template i experienced this error:

```
    "resources": [
      {
        "apiVersion": "2017-04-26-preview",
        "type": "Microsoft.DevTestLab/labs/virtualmachines",
        "name": "[variables('vmName')]",
        "location": "[resourceGroup().location]",
        "properties": {
          "labVirtualNetworkId": "[variables('labVirtualNetworkId')]",
          "notes": "Ubuntu Server 16.04 LTS",
...............
          "labSubnetName": "[variables('labSubnetName')]",
          "disallowPublicIpAddress": false,
          "storageType": "Premium",
          "allowClaim": false
        }

```

**Comment by leovms** [comment]
@lukka, than you for the information. I'll be taking a look at this and have a resolution by next week.

**Comment by leovms** [comment]
@lukka, I've re-tested the logic around property `disallowPublicIpAddress`. I can confirm that it's behavior is by design. That is, if you re-run the ARM template a second time, without changes to the property value, the deployment completes without error, as expected. It is only when attempting to change the original value that the aforementioned error occurs, as expected since this value cannot be changed.
