### ISSUE TITLE
windows-visualstudio artifact command line args clash

### ISSUE THREAD

**Issue by richardhauer** [Azure/azure-devtestlab#387]
Having the option to specify command line args is excellent, because you can customise the workloads that get installed.  That's all wasted, though, if the default installation process adds all the workloads on top of your custom arguments, and since the blade does not provide options for which workloads are installed by default, you can't tell what's going on.  Can I suggest that if custom arguments are supplied, these should replace the default arguments, rather than adding to them.  You could even check for which arguments had been supplied and make some intelligent choices, e.g. if there's no `--log` argument then add it, if there's a `--q` argument provided you don't need to add `--quiet`, etc.

Is it possible to customise the Add Artifact blade to allow users to specify the workloads to be installed? Happy to do it and submit a PR - we use this all the time.

Further, the `--wait` option that is force-added by the script seems to cause an error (possibly only when the `--q` is removed, more testing needed) in VS 2017 Enterprise.

**Comment by tanmayeekamath** [comment]
Hi Richard,
We do accept PRs to add specific artifacts to the repo if it has a common usecase. 
If not, we request you to create a private repo with relevant artifacts for you. 
You can see more docs on authoring artifacts here: https://docs.microsoft.com/en-us/azure/lab-services/devtest-lab-artifact-author
