### ISSUE TITLE
Download VSTS Drop and Run Script doesn't work with large files

### ISSUE THREAD

**Issue by kitsuneplusplus** [Azure/azure-devtestlab#388]
Expected: Artifact downloads VSTS artifacts without issue
Actual: Artifact fails to run with error: Exception of type 'System.OutOfMemoryException' was thrown.

at:
Preparing to download artifact installers to file installers.zip
Downloading artifact installers from https://url.removed.for.security&api-version=2.0&%24format=zip
ERROR: Exception of type 'System.OutOfMemoryException' was thrown.

Using: windows-vsts-download-and-run-script
From: https://github.com/Azure/azure-devtestlab/tree/master/Artifacts/windows-vsts-download-and-run-script
Commit: 9fc902b

It should be noted that smaller zips do download fine. I have tried splitting artifacts up into separate folders, but to no avail. Our artifacts do end up being quite large as they are the installers for a large suite of engineering analysis software. The problem seems to lay with the Invoke-RestMethod cmdlet but I can't find any hard limits on the size of retrieved files. Please help! We wanna use devtestlabs!
The large zip is 4.1-4.3GB

**Comment by tanmayeekamath** [comment]
Apologies for the delay. 
We made improvements to the artifacts in labs since. Are you still experiencing these issues?
