### ISSUE TITLE
How to start multiple VM in DevTest Lab

### ISSUE THREAD

**Issue by Evit15** [Azure/azure-devtestlab#393]
Hi,

Do I can use Azure CLI to start multiple VM in 1 DevTest Lab?
I see in help, I only start a VM

**Comment by tanmayeekamath** [comment]
Yes you can use our rest api to start multple lab VMs. 
Please take a look at this doc for the same: https://docs.microsoft.com/en-us/rest/api/dtl/virtualmachineschedules/update

Hope this helps!

**Comment by Evit15** [comment]
Thanks @tanmayeekamath . I will try it.

Do you have the plan to support Rest API of DevTest Lab in Azure CLI?

**Comment by tanmayeekamath** [comment]
You can find the CLI commands supported for DevTest Labs here: https://docs.microsoft.com/en-us/cli/azure/lab?view=azure-cli-latest
Are these helpful?

**Comment by Evit15** [comment]
Hi @tanmayeekamath ,

Now, CLI commands only support to start a VM in a DevTest Lab, it does not support to start multiple machine.

Please re-check it.

Thanks!

**Comment by tanmayeekamath** [comment]
We had a blog post that I uses Azure Automation to start multiple DTL VMs in order. However, we are in the process of migrating it to our docs as our blog was retired recently. 
I can share a word copy with you until then if you can share your email with me? 

Tanmayee

**Comment by Evit15** [comment]
My email is "xuanhieu1989@gmail.com"

Thanks for your share!
