### ISSUE TITLE
ARM template with secrets for all users

### ISSUE THREAD

**Issue by smokedlinq** [Azure/azure-devtestlab#400]
I am trying to compose an ARM template that adds a secret to all users. I can add it to the key vault but they don't see the secret. If I try to use the ARM resource for user secrets, it only works for my users, but for other users it returns an error (my user is an owner on the subscription):

```
  "error": 
    "code": "IdentityPropertiesDontMatch", 
     "message": "Identity properties provided with this request do not match the context of this request."
```

**Comment by tanmayeekamath** [comment]
Thanks for reaching out and apologies for the delay. Secrets work on per user basis in a lab. That means you as a lab user can only view your secrets. 
We have a feature to allow adding team secrets that would allow lab users to share them. We will update you once we have a timeline for implementation.

**Comment by Synomax** [comment]
I still can't find this feature. Where is the documentation about this implementation?
