### ISSUE TITLE
"window-winrm" artifact applied fail on Win 10 clean machine

### ISSUE THREAD

**Issue by Evit15** [Azure/azure-devtestlab#402]
Hi,

On Win 10 clean machine, I applied "window-winrm" artifact but it failed with below error:

> WSManFault
    Message = The client cannot connect to the destination specified in the request. Verify that the service on the destination is running and is accepting requests. Consult the logs and documentation for the WS-Management service running on the destination, most commonly IIS or WinRM. If the destination is the WinRM service, run the following command on the destination to analyze and configure the WinRM service: "winrm quickconfig". 
Error number:  -2144108526 0x80338012
The client cannot connect to the destination specified in the request. Verify that the service on the destination is running and is accepting requests. Consult the logs and documentation for the WS-Management service running on the destination, most commonly IIS or WinRM. If the destination is the WinRM service, run the following command on the destination to analyze and configure the WinRM service: "winrm quickconfig".

I think "winrm" service does not start.
Please help me check

**Comment by leovms** [comment]
Resolved with commit #403.
