### ISSUE TITLE
Download VSTS Drop and Run Script doesn't work with saved secret

### ISSUE THREAD

**Issue by dschmackweg** [Azure/azure-devtestlab#405]
When using this task with the Saved Secret option, I always get an error where if I use the same Personal Access Token directly it will work.  I have tried recreating both the secret and the PAT with the same results.

```
Provided parameters used in this script:
  $accessToken = ***************************
  $buildDefinitionName = xxxxxxxx
  $vstsProjectUri = https://xxxxxxxx.visualstudio.com/defaultCollection/xxxxxxxx
  $pathToScript = drop\xxxxxxxx.ps1
  $scriptArguments = 
Variables used in this script:
  $vstsApiVersion = 2.0
  $outfile = 
  $destination = \xxxxxxxx
Getting build definition ID from https://xxxxxxxx.visualstudio.com/defaultCollection/xxxxxxxx/_apis/build/definitions?api-version=2.0&name=xxxxxxxx
ERROR: Cannot index into a null array.
```

Note that if I load `https://xxxxxxxx.visualstudio.com/defaultCollection/xxxxxxxx/_apis/build/definitions?api-version=2.0&name=xxxxxxxx`  myself, it works just fine as well.

**Comment by tanmayeekamath** [comment]
Apologies for the delay. Are you still experiencing this issue?

**Comment by dschmackweg** [comment]
I believe I switched to an altogether different approach to getting my files so, I do not know if this is still an issue.
