### ISSUE TITLE
subnet 'xxx' either is not enabled or is not part of specified virtual network

### ISSUE THREAD

**Issue by aatif912** [Azure/azure-devtestlab#418]
Hi,

I have created a DTL using template from here - 
[https://github.com/Azure/azure-devtestlab/blob/master/Samples/101-dtl-create-lab/azuredeploy.json](https://github.com/Azure/azure-devtestlab/blob/master/Samples/101-dtl-create-lab/azuredeploy.json)

After that i am changing the subnet and creating a P2S VPN using below script-
```
$VNetName = "dtlinfratest2"
$RG = "infratest2"
$Location = "westeurope"
$MyP2SRootCertPubKeyBase64 = "XXXXXXX"

# each virtaul network is inside a dev test lab so below values can hold good for all cases.
# Note: This is going to fail if VM exists in the virtual network
$GWSubName = "GatewaySubnet"
$VNetPrefix1 = "10.0.0.0/16"
$SubPrefix = "10.0.0.0/24"
$GWSubPrefix = "10.0.200.0/26"
$VPNClientAddressPool = "132.16.201.0/24"
$GWName = "GateWay"
$GWIPName = "GateWayIP"
$GWIPconfName = "GateWayIPConfig"

$vnet = Get-AzureRmVirtualNetwork -Name $VNetName -ResourceGroupName $RG

$fesub = New-AzureRmVirtualNetworkSubnetConfig -Name $vnet.Subnets.name -AddressPrefix $SubPrefix
$gwsub = New-AzureRmVirtualNetworkSubnetConfig -Name $GWSubName -AddressPrefix $GWSubPrefix
$vn = New-AzureRmVirtualNetwork -Name $VNetName -ResourceGroupName $RG -Location $Location -AddressPrefix $VNetPrefix1 -Subnet $fesub, $gwsub -Force

$subnet = Get-AzureRmVirtualNetworkSubnetConfig -Name $GWSubName -VirtualNetwork $vn

$pip = New-AzureRmPublicIpAddress -Name $GWIPName -ResourceGroupName $RG -Location $Location -AllocationMethod Dynamic
$ipconf = New-AzureRmVirtualNetworkGatewayIpConfig -Name $GWIPconfName -Subnet $subnet -PublicIpAddress $pip

$p2srootcert = New-AzureRmVpnClientRootCertificate -Name "P2SVNETRootCertName" -PublicCertData $MyP2SRootCertPubKeyBase64
New-AzureRmVirtualNetworkGateway -Name $GWName -ResourceGroupName $RG -Location $Location -IpConfigurations $ipconf -GatewayType Vpn -VpnType RouteBased -EnableBgp $false -GatewaySku Standard -VpnClientAddressPool $VPNClientAddressPool -VpnClientRootCertificates $p2srootcert 

```
I am creating VMs without any issues in the subnet and after a pre-defined time the VMs are expiring and after that I observed that the VM creation is failing inside the lab. Error Message-
_Subnet DtlInfraTest2Subnet either is not enabled or is not part of specified virtual network 
/subscriptions/XXXXX/resourcegroups/infratest2/providers/microsoft.devtestlab/labs/infratest2/virtualnetworks/dtlinfratest2_

I checked the network tab inside the lab and found that the "**USE IN VIRTUAL MACHINE CREATION**" is off and unless I tick that green manually I am not able to create VM.
![image](https://user-images.githubusercontent.com/13832737/47012507-f1966b80-d161-11e8-9d97-3a440d2c222d.png)

I tried searching for a powershell command but couldn't find one. By default when we create the VM using template the "**USE IN VIRTUAL MACHINE CREATION**" but goes off when all the VMs expire automatically.

**Comment by tanmayeekamath** [comment]
Apologies for the delay! Are you still experiencing this issue?

**Comment by aatif912** [comment]
This issue still persists.

**Comment by leovms** [comment]
@aatif912, from the image I see that the subnet in question is NOT enabled for `use in virtual machine creation`. That's the root cause of your error. This needs to be enabled in the Lab under `Configuration and policies` / `Virtual networks`, before you can use the subnet to create VMs.
