### ISSUE TITLE
ARM Template Web App with MySQL Failing

### ISSUE THREAD

**Issue by marcodehaan** [Azure/azure-devtestlab#432]
When creating a new instance from Template "Web App with MySQL" the creation fails. The activity Log states that the speficied api version is not supported. Up until today it worked fine. Details from activity log below. Could you update the json file to the supported api versions.

**Error code**
NoRegisteredProviderFound
**Message**
No registered resource provider found for location 'westeurope' and API version '2016-02-01-privatepreview' for type 'servers'. The supported api-versions are '2017-12-01-preview, 2017-12-01'. The supported locations are 'australiacentral, australiacentral2, australiaeast, australiasoutheast, brazilsouth, canadacentral, canadaeast, centralindia, centralus, eastasia, eastus2, eastus, francecentral, japaneast, japanwest, koreacentral, koreasouth, northcentralus, northeurope, southcentralus, southindia, southeastasia, ukwest, uksouth, westeurope, westindia, westus, westus2'.

The file with the updated code is attached in this issue, we tested it and this one seems to work just ok.
[azuredeploy.txt](https://github.com/Azure/azure-devtestlab/files/2868705/azuredeploy.txt)

**Comment by tanmayeekamath** [comment]
Thanks for reporting this. We will update the API version.

**Comment by tanmayeekamath** [comment]
We have fixed this now.
