### ISSUE TITLE
Azure Pipelines Deployment Group Agent artifact has different icon

### ISSUE THREAD

**Issue by NenoLoje** [Azure/azure-devtestlab#435]
[Low Priority]

It looks like the [Azure Pipelines Deployment Group Agent artifact](https://github.com/Azure/azure-devtestlab/tree/master/Artifacts/windows-deploymentgroup) (windows-deploymentgroup) has a different icon than the other Pipline Agent-related tasks. Was that done on purpose?

![grafik](https://user-images.githubusercontent.com/13981145/53110946-69273d80-353c-11e9-95fe-6e8190026d48.png)

Thanks,
--Neno

**Comment by leovms** [comment]
Please look at [this commit](https://github.com/leovms/azure-devtestlab/commit/089266f9fbb61c266e20872e6577ed9058d89855) for the changes to the `artifactfile.json` where we now reference the correct icon.
