### ISSUE TITLE
Pipelines Agent artfact fails with ERROR: Pool {pool-id} already contains an agent with name {agent-name}

### ISSUE THREAD

**Issue by NenoLoje** [Azure/azure-devtestlab#436]
Here's the setup:
- Azure Pipelines
- [DevTest Labs Create VM task](https://github.com/Azure/azure-devtestlab/tree/master/VstsTasks/AzureDtlCreateVM) (AzureDtlCreateVM)
- The [Pipelines Agent artifact](https://github.com/Azure/azure-devtestlab/tree/master/Artifacts/windows-vsts-build-agent) (windows-vsts-build-agent)

Creating the VM for the first time, and registering the agent works great.
However, running the same pipleline a second time fails with:

> ERROR: Pool {pool-id} already contains an agent with name {agent-name}

While this is correct, I wonder what the recommendation is in this case?

It seems that the Pipelines Agent has a parameter called `--replace` when configuring the piplines agent, that might help with this and which the Pipelines Agent artifact is currently not using/offering.

Thanks,
--Neno

**Comment by leovms** [comment]
I took a look at the commands. It seems that `--replace` will "Replace the agent in a pool. If another agent is listening by that name, it will start failing with a conflict." The assumption to use replace would be that the agent name will always be unique.

Would another option to consider be to do a `./config.cmd remove`, followed by the new configuration? 

To support the scenario, we would add a parameter called `Replace Agent`, or similar; where if set, we simply 1. use the `--replace` parameter, or 2. remove it and reconfigure it. Which would be the preferred approach for your scenario, or in general?

**Comment by NenoLoje** [comment]
@leovms: Thanks! Option 1 seems like the way to go. Let me verify and come back to you.

**Comment by leovms** [comment]
@NenoLoje, I've since created [this PR](https://github.com/Azure/azure-devtestlab/pull/460) with the changes. As soon as you confirm this takes care of your scenario, I'll integrate the changes to the Public Repo. Thanks.

**Comment by leovms** [comment]
Updates have been done to the corresponding artifact. Please retry and re-open, as needed.

**Comment by dazinator** [comment]
@leovms is this only for the windows agent? I have a similar situation with a self hosted containerised agent - running as linux container.

>  agent v3.227.1             |_|          (commit ba93fcd)
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    |
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    |
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    | >> End User License Agreements:
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    |
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    | Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    |
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    | A copy of the Team Explorer Everywhere license agreement can be found at:
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    |   /azp/license.html
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    |
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    |
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    | >> Connect:
azure-devops-agents_devops-pipelines-agent.1.78xay96u9b5i@swarm-mgr-02    | Connecting to server ...
azure-devops-agents_devops-pipelines-agent.1.78xay96u9b5i@swarm-mgr-02    |
azure-devops-agents_devops-pipelines-agent.1.78xay96u9b5i@swarm-mgr-02    | >> Register Agent:
azure-devops-agents_devops-pipelines-agent.1.78xay96u9b5i@swarm-mgr-02    |
azure-devops-agents_devops-pipelines-agent.1.78xay96u9b5i@swarm-mgr-02    | Scanning for tool capabilities.
azure-devops-agents_devops-pipelines-agent.1.78xay96u9b5i@swarm-mgr-02    | Connecting to the server.
azure-devops-agents_devops-pipelines-agent.1.78xay96u9b5i@swarm-mgr-02    | Pool  already contains an agent with name swarm-mgr-02.
azure-devops-agents_devops-pipelines-agent.1.78xay96u9b5i@swarm-mgr-02    | Environment with id '4' already contains a virtual machine resource with name 'swarm-mgr-02'.
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    |
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    | Connecting to server ...
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    |
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    | >> Register Agent:
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    |
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    | Scanning for tool capabilities.
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    | Connecting to the server.
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    | Pool  already contains an agent with name swarm-mgr-02.
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    | Error reported in diagnostic logs. Please examine the log for more details.
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    |     - /azp/_diag/Agent_20231004-224153-utc.log
azure-devops-agents_devops-pipelines-agent.1.wqx9sco87gj6@swarm-mgr-02    | Environment with id '4' already contains a virtual machine resource with name 'swarm-mgr-02'.
azure-devops-agents_devops-pipelines-agent.1.78xay96u9b5i@swarm-mgr-02    | Error reported in diagnostic logs. Please examine the log for more details.
azure-devops-agents_devops-pipelines-agent.1.78xay96u9b5i@swarm-mgr-02    |     - /azp/_diag/Agent_20231004-224057-utc.log
