### ISSUE TITLE
Azure Pipelines Deployment Group Agent does not set deployment group tags correctly

### ISSUE THREAD

**Issue by NenoLoje** [Azure/azure-devtestlab#439]
When using the [Azure Pipelines Deployment Group Agent artifact](https://github.com/Azure/azure-devtestlab/tree/master/Artifacts/windows-deploymentgroup), I noticed that whatever I enter as **Deployment agent tags**, the Deployment Group gets created without any tags.

Maybe the PowerShell script is missing the `--adddeploymentgrouptags` parameter?

![grafik](https://user-images.githubusercontent.com/13981145/53210864-9872a300-363f-11e9-911e-e23be90cd522.png)
Figure: Screenshot from the freshly Deployment Group. No tags have been set.

Thanks,
--Neno

**Comment by DeChrist** [comment]
Hi Neno,

you beat me on reporting this one!

The information I collected follows:

The artifact installation succeeds but the Tags provided as parameters are not set.
The Tags are correctly visible in the input of the Artifact.
The VM is correctly displayed in the ADO Deployment Group but wihout any associated tag.

I investigated this a bit further and there is apparently an additional parameter named "--addDeploymentGroupTags" that is not set in the Artifact PowerShell (reference: https://github.com/Microsoft/azure-pipelines-agent/issues/1046#issuecomment-311855101).

The line of code to update:
https://github.com/Azure/azure-devtestlab/blob/063991aaf20790b3aa02389f40f14f9e970967b3/Artifacts/windows-deploymentgroup/InstallAndConfigureDeploymentGroupAgent.ps1#L252

Do you intend to create a PR for fixing this? If yes, go for it, if not, I will.

**Comment by NenoLoje** [comment]
Awesome - thanks, @DeChrist, for investigating and creating the PR!
Do you need anything from me to get this approved?

**Comment by DeChrist** [comment]
Hi,

it could help if you can indepently confirm that the fix closes the issue but it is so simple that this should not be needed.

@leovms is aware of the incoming PR

Christian D.
