### ISSUE TITLE
Pipelines Agent artfact (with autologon = true) doesn't come online on Win 10

### ISSUE THREAD

**Issue by NenoLoje** [Azure/azure-devtestlab#441]
I'm trying to use the [Pipelines Agent artifact](https://github.com/Azure/azure-devtestlab/tree/master/Artifacts/windows-vsts-build-agent) (windows-vsts-build-agent) to setup a new agent`:
- using Azure's **Windows 10 Pro** image
- configured interactively (with autologon = true)
- with the goal to run UI Tests on it (through Azure Pipelines).

**What's happening:**
While the agent configuration succeeds (an entry is created in Agent Pool on Azure Piplines), it shows as offline.

**What we have tried so far:**
After logging in to this VM manually, I can see this screen:

![grafik](https://user-images.githubusercontent.com/13981145/53411537-019f4100-39c7-11e9-9f9e-2a91c7286603.png)

After confirming this screen and restarting the VM manually, the agent comes up as expected.

**Question**:
Any ideas/hints what we can do, so the agent comes 'online' without the need for manual intervention?

Thanks,
--Neno

**Comment by DeChrist** [comment]
Hi Neno,

I ran into a similar issue and I don't know how to resolve the issue.
However, I have found a workaround that worked for me.

Thanks to confirmation of:

1. Is your scenario similar?
2. The workaround works for you

**Test scenario:**
- Provisioning of the VM is successful (through a Release Pipeline)
- Registration as Agent in the DG is initially successful (shows "Online" then "Offline")
- Machine reboots itself for "autologon" (and readiness for interactive tests)

Expected:
- The VM starts, logs in automatically, and stars the agent in a Console

Actual:
- The VM is "running" but never registers again
  - So I suspect the VM is blocked on the screen you have attached

**Workaround** 
- In the Pipeline, Stop the VM, and then Start it again
  - The tests I run have a screen recorder configured where I can see that it works as "Expected"

Best regards,
Chris.

**Comment by leovms** [comment]
@DeChrist, if we restart the VM after adding the agent, do you think it will solve the issue? It seems from the workaround above, that it should do the trick. Can you please confirm?

**Comment by leovms** [comment]
Updates have been done to the corresponding artifact. Please retry and re-open, as needed.

**Comment by Evit15** [comment]
Hi @leovms 

This issue still happens. 
Do you have any workaround for it ?

**Comment by leovms** [comment]
@Evit15, workaround is described above. If that does not work for you, it may be that there's another issues at play. If so, please open a new request and describe in detail your observations.

**Comment by Evit15** [comment]
Hi @leovms 
The workaround does not work both image win 10 1809 and 1903
The step to reproduce and expect as @NenoLoje posted. I think we only need reopen this issue.

**Comment by karthi327** [comment]
@NenoLoje @Evit15 @leovms I am still facing the same issue mentioned in the steps to reproduce. My agent is not coming online and I am seeing the same screen when logged in manually. I even tried the workaround: stop and start the vm, it did not worked out. could any of you please let me know how to fix this?
