### ISSUE TITLE
Feature Request: Create an artifact that checks for and installs Windows Updates

### ISSUE THREAD

**Issue by clisc** [Azure/azure-devtestlab#443]
Scenario:

I'm creating a new VM to sysprep and use as a custom VHD image.  I want to apply all necessary artifacts and all Windows Updates before I sysprep the VM.

However, I have not been able to connect to the VM.  Therefore, I can't log in and do the Windows Updates myself.

It would be nice to have an artifact called "Install Windows Updates" that checks for updates, installs them, reboots as needed, and repeats until no more updates are found.

**Comment by tanmayeekamath** [comment]
Thanks for the feedback. 
We don't have this artifact as of today. I have created a [User Voice entry](https://feedback.azure.com/forums/320373-lab-services/suggestions/37195387-artifact-to-install-windows-updates) for the same. We prioritize features based on customer votes for the same.

In the meantime, you can follow this doc to learn more on authoring artifacts: https://docs.microsoft.com/en-us/azure/lab-services/devtest-lab-artifact-author

Hope this helps.
