### ISSUE TITLE
Add Support for the OSDisk object

### ISSUE THREAD

**Issue by Naninani** [Azure/azure-devtestlab#452]
Currently the DTL ARM templates does not support the OSDisk object like the regular [VM ARM templates](https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/2018-10-01/virtualmachines).
We need an option to configure the OS disk size when creating Linux VM's. We have a pool of hundreds of Linux VM's in ADTL used as ADO build agents and the default OS disk size of 30GB is not enough.
There is no good way to automate the resizing of the OS disk nor attaching new data disks on Linux.

**Comment by tanmayeekamath** [comment]
Hi Stanislav,
Thanks for your feedback. Let me get back to you on this by tomorrow. 

Tanmayee

**Comment by tanmayeekamath** [comment]
Hi Stanislav,
This would qualify as a new featured request as we don't support this scenario in DTL today.
Can you please post this at our user voice forum here: https://feedback.azure.com/forums/320373-devtest-labs
We prioritize features based on customer votes on the same. 

Thanks,
Tanmayee
