### ISSUE TITLE
Cant change the OS disk type in Formula

### ISSUE THREAD

**Issue by Naninani** [Azure/azure-devtestlab#455]
Looks like there was a recent update of ADTL that introduces this issue. Looking at all the formulas that we have all disk types are set from Premium SSD to Standard HDD. Choosing Premium SSD from the drop down menu and saving the formula does not actually apply the changes and when editing the formula again the disk settings are set back to Standard HDD.

**Steps to reproduce**:
1. Edit existing formula in ADTL.
![image](https://user-images.githubusercontent.com/1681582/55519439-ae0abd80-562c-11e9-9be6-689f4bb0d393.png)
2. Set the "OS disk type" to "Premium SSD".
![image](https://user-images.githubusercontent.com/1681582/55519461-cbd82280-562c-11e9-9237-b72d2c96a25e.png)
3. Save the formula and w8 for Az to complete the deployment.
4. Edit the formula again.

**Current result**:
The "OS disk type" is set back to "Standard HDD". Checking the ARM template confirm it. It is not that we dont have access to Premium SSD, as we can successfully deploy ARM template with "storageType": "Premium"

**Expected Result**:
The "OS disk type" should be set to "Premium SSD".

**Comment by leovms** [comment]
The issue you are describing is on the Azure Portal extension for DevTest Labs. You can get assistance by navigating to your lab and then go to "Diagnose and solve problems". On that page, there's a link to generate a "support request". Please submit the issue using that method.

**Comment by tanmayeekamath** [comment]
Hi Stanislav,
Thanks for the feedback.
We have created a bug for this and we will be fixing this behavior. I will send an update once the bug is fixed. 

Going forward, please post bugs either on our [MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=AzureDevTestLabs&filter=unanswered&sort=lastpostdesc) or through a support ticket. 

Thanks,
Tanmayee
