### ISSUE TITLE
Arm Template Location for DTL

### ISSUE THREAD

**Issue by mainray99** [Azure/azure-devtestlab#462]
Can someone point me to the location of the DevTestLab Arm Templates.  I was able to find them earlier today but now I cannot.

Thanks

**Comment by michaelwstark** [comment]
The quick start templates?  They were moved as part of a PR to re-structure the repo.
https://github.com/Azure/azure-devtestlab/tree/master/samples/DevTestLabs/QuickStartTemplates

PR:
https://github.com/Azure/azure-devtestlab/commit/2add6360ab915e73ef50aebd21f53a628f4c9263

**Comment by mainray99** [comment]
Perfect Thanks!
