### ISSUE TITLE
Create a new DevTestLab instance

### ISSUE THREAD

**Issue by jecaestevez** [Azure/azure-devtestlab#467]
When I tried to deploy https://github.com/Azure/azure-devtestlab/tree/master/samples/DevTestLabs/QuickStartTemplates/301-dtl-create-lab-with-remote-desktop-settings
I had the bellow error , any idea what's wrong?
> There was an error loading the template from URI 'https://raw.githubusercontent.com/Azure/azure-devtestlab/master/Samples/301-dtl-create-lab-with-remote-desktop-settings2Fazuredeploy.json'. Ensure that the template is publicly accessible and does not have any comments.

**Comment by leovms** [comment]
Apologies for the inconvenience. We have recently restructured the repo. It seems that somehow a reference to the old path is being made. Can you tell me how you are using the ARM template?

**Comment by leovms** [comment]
@felipecruz91, thank you for your PR. I've updated all the documentation to reference the links correctly. So, some others that are currently broken will be fix with #468.
