### ISSUE TITLE
Issue in importvirtualmachines.ps1 when additional disks are attached

### ISSUE THREAD

**Issue by hintbw** [Azure/azure-devtestlab#470]
We are successfully using importvirtualmachines.ps1 when VMs don't have additional disks, but when we have additional disks it seems to fail with the following error:

CreatingOrUpdatingOnlyAllowedForCurrentUser : Creating or updating resources is only allowed for the current user.
Allowed values for user name: [a31d5170-9ad3-47f8-a1f7-27ce199923a1, @me].
    + CategoryInfo          : CloseError: (:) [Invoke-AzureRmResourceAction], ErrorResponseMessageException
    + FullyQualifiedErrorId : CreatingOrUpdatingOnlyAllowedForCurrentUser,Microsoft.Azure.Commands.ResourceManager.Cmd
   lets.Implementation.InvokAzureResourceActionCmdlet
    + PSComputerName        : localhost

Failed to migrate VM 'AtlasDemo' from Lab 'PlatformDataGovernanceTestLab' to Lab 'DGXDtl'
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException
    + PSComputerName        : localhost

![2019-04-15 18_31_12-Activity log - Microsoft Azure](https://user-images.githubusercontent.com/7452113/56175612-c673c400-5fac-11e9-99db-3185e30f90ad.png)
![2019-04-15 18_31_46-Create a virtual machine - Microsoft Azure](https://user-images.githubusercontent.com/7452113/56175613-c673c400-5fac-11e9-943e-6a28d02ead76.png)

**Comment by leovms** [comment]
@hintbw, thank you for reporting the issue. Before starting to review the scenario, can you please confirm the repro steps?

**Steps to Reproduce**

1. Create a new or use an existing lab (i.e. `MyLab1`).
2. Create Lab VM (i.e. `MyVm1`) of type Linux or Windows in `MyLab1`.
3. Add a new disk (i.e. `MyDataDisk1`).
4. Create a new or use an existing lab (i.e. `MyLab2`).
5. Execute the script as follows:
    ```PS1
    ./ImportVirtualMachines.ps1 -SourceSubscriptionId 'MySub1' -SourceDevTestLabName 'MyLab1' -SourceVirtualMachineName 'MyVm1' -DestinationSubscriptionId 'MySub2' -DestinationDevTestLabName 'MyLab2' -DestinationVirtualMachineName 'MyVm2'
    ```
6. Observe reported error.

**Comment by hintbw** [comment]
@leovms Those are the steps to reproduce, the one addition is that there are two data disks

**Comment by leovms** [comment]
Thank you. Let me take a look.

**Comment by hintbw** [comment]
I'm also happy to submit an Azure Support incident and share the ticket number if that would help get access to any logs that might be helpful. We've had a team that migrated 5 different machines over the weekend all of which didn't have more than just an OS disk.

**Comment by leovms** [comment]
As you wish. I'm first going to run through the scenario and try to repro it. If I can repro it, then I'll enter a bug in our system and get it worked on.

**Comment by leovms** [comment]
@hintbw, I just completed a test run on the script. It did successfully create a new VM with the 2 data disks. Can you tell me if the user executing the script owns the source VM and the target lab? Is there something you can share about the permissions of the user executing the script, as it pertains to the source and destination subscriptions/labs/VMs?

**Comment by hintbw** [comment]
I am the one running the script. I am an owner (RBAC role) on the source lab and VM and the target lab. I did some more investigation and I believe there is more to the repo steps that are required. It appears that there were 2 disks with the same names as the data disks being migrated that already existed in the destination subscription. Given the error about updating an existing resource, perhaps that might be related (my user didn't have permissions on those disks). The disks that existed in the destination subscription were unattached so I'm deleting them and am going to try the migration again and will report back when it finishes.

In the case of your repro steps, it would be interesting to see if, when similar disks already existed in the destination subscription, the migration also fails. In my case, the disks were not even in the same resource group as the destination devtest lab.

**Comment by hintbw** [comment]
Unfortunately, even with removing those two data disks in the destination subscription, I received the same error message. It failed on the same step with disks - which I don't understand. I've compared what we are doing between this lab and another lab and still can't understand why there is a failure.

**Comment by leovms** [comment]
On my side, I've not being able to repro your reported error either. Are you able to create another lab and try the same operation there? Unfortunately, without a repro, I'm afraid I can't do much to help.

**Comment by leovms** [comment]
@hintbw, I'll be closing this issue. If you come up with new information that can help us repro the scenario, please feel free to re-open it. We'll be happy to take a look again.
