### ISSUE TITLE
Having trouble with Windows-VSCode artifact

### ISSUE THREAD

**Issue by TCourtneyOwen** [Azure/azure-devtestlab#472]
I am trying to add the Windows-VsCode artifact to a VM in my DevTest lab via PowerShell and am not having any luck. Here's my script:

$labName = 'OPX-Dev-Test-Lab'
$resourceGroup = 'OPX-VHDs'
$vmName = 'opx-azure-01'
$artifact = 'https://github.com/Azure/azure-devtestlab/blob/master/Artifacts/windows-vscode/Artifactfile.json'

az lab vm apply-artifacts --lab-name $labName --name $vmName --resource-group $resourceGroup --artifacts @$artifact

I get the following unhelpful error:

az : ERROR: Expecting value: line 1 column 1 (char 0)
At line:6 char:1
+ az lab vm apply-artifacts --lab-name $labName --name $vmName --resour ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Expectin...lumn 1 (char 0):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Does something look wrong with my script? Am I not specifying the artifact in the correct manner?

Thanks,

Courtney

**Comment by leovms** [comment]
Hi Courtney,

Please refer to the section called [Update the virtual machine](https://docs.microsoft.com/en-us/azure/lab-services/devtest-lab-vmcli#update-the-virtual-machine) for an example on how to apply artifacts using the CLI.

Here's a specific example for your ask,

``` PS1
$SubId = '<YourSubId>'
$LabName = '<YourLabName>'
$VmName = '<YourVmName>'
$RgName = '<YourLabRgName>'
$Artifacts = @"
[
  {
    "artifactId": "/artifactSources/public repo/artifacts/windows-vscode",
    "parameters": []
  }
]
"@
$ArtifactsPath = "${env:Temp}\artifacts.json"

[IO.File]::WriteAllText($ArtifactsPath, $Artifacts)

az lab vm apply-artifacts --lab-name $LabName --name $VmName --resource-group $LabRgName --subscription $SubId --artifacts @$ArtifactsPath
```

The `--artifacts` parameter expects a JSON array of relative artifact definitions. You were passing the URL to the `artifactsfile.json`, which is not correct. If you use a file, like in the above example, you want to write the JSON array to it.

**Comment by TCourtneyOwen** [comment]
Thanks for the info. I was able to figure the problem. Much appreciated. 

-Courtney
