### ISSUE TITLE
Windows-Sysprep artifact timing out

### ISSUE THREAD

**Issue by TCourtneyOwen** [Azure/azure-devtestlab#473]
@leovms I am finding that when I try to apply window-sysprep artifact to a VM created from the "Windows 10 Enterprise for Virtual Desktops Preview 1809 + Office365" base image that the operation times out.  Any idea why this might be happening? I am pretty unfamiliar with sysprep and haven't had much luck with it when I run it manually either.

Thanks,

Courtney

**Comment by leovms** [comment]
@TCourtneyOwen, can you confirm if you're still experiencing timeout issues with the `sysprep` artifact?

**Comment by TCourtneyOwen** [comment]
I confirmed that I am no longer experiencing the timeout - it takes about five minutes to sysprep my vm with the artifact and this is sufficient. Thanks!
