### ISSUE TITLE
DevTest Labs security model

### ISSUE THREAD

**Issue by joaocosta** [Azure/azure-devtestlab#483]
I have an account in a corporate Azure subscription.  My account has the roles "DevTest Labs User" and "Reader" assigned at the Resource Group level, and I am able to create VMs using the portal and the Azure CLI.  When I try to create a VM using terraform, I get the error:

`
Code="AuthorizationFailed" Message="The client 'joao.costa@xxx.com' with object id 'xxx' does not have authorization to perform action 'Microsoft.DevTestLab/labs/virtualmachines/write' over scope '/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.DevTestLab/labs/DevTestLabPoc/virtualmachines/xxx'
`

I can see someone else reporting similar behaviour ( can create a VM through portal and CLI, but not SDK ) at https://github.com/Azure/azure-sdk-for-python/issues/4379.

My question is, why am I able to create a VM through the portal and the CLI but not the SDK ?

**Comment by leovms** [comment]
@joaocosta, please submit the issue either on our [MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=AzureDevTestLabs&filter=unanswered&sort=lastpostdesc) or through a support ticket.

You can create a support ticket by navigating to your lab and then going to `Diagnose and solve problems`. On that page, there's a link to generate a `support request`.
