### ISSUE TITLE
Create lab with ARM and assign Contributor to resource group user rights?

### ISSUE THREAD

**Issue by ChrisLGardner** [Azure/azure-devtestlab#484]
When deploying a new DevTest Lab via ARM template is it possible to set the Environment Access to Contributor from the default Reader? I couldn't see anything in resources.azure.com after I'd made the change to an existing lab which makes me think it's not possible. Is it possible in some other way such as PowerShell or Az CLI? 

I have users who are self provisioning Labs using the ARM template (from an Azure Pipeline) but they then can't modify any environments deployed within that Lab as they aren't contributors on the resource groups created by the Lab.

**Comment by leovms** [comment]
@ChrisLGardner, in future, please submit such inquiries either on our [MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=AzureDevTestLabs&filter=unanswered&sort=lastpostdesc) or through a support ticket. The issues section in this repo is for reporting problems with the content in the repo.

You can create a support ticket by navigating to your lab and then going to Diagnose and solve problems. On that page, there's a link to generate a support request.

BTW, if a user creates a lab, he's automatically able to create environments. So, it may be that someone else is creating the labs for them. In that case, the above property, added to the ARM template used to create the lab, should do the trick.

Having said that, you can try setting the lab property called `environmentPermission` to the value `Contributor`. For more information, take a look at the doc [Lab - Create or Update](https://docs.microsoft.com/en-ca/rest/api/dtl/labs/createorupdate?view=azureadps-2.0-preview).
