### ISSUE TITLE
[AZ.DEVTESTLABS]  Library doesn't work on Azure Powershell 5.x

### ISSUE THREAD

**Issue by petehauge** [Azure/azure-devtestlab#494]
When using the DevTest Labs azure module, even running basic commands like "Dtl-GetLab" fails.  
![libraryerror](https://user-images.githubusercontent.com/12090616/58667221-70ac6e80-8303-11e9-9216-dbb0f8d8bc45.png)

The underlying cause is approx. line 80:
    Get-AzureRmResource -ExpandProperties -resourcetype $ResourceType -EA SilentlyContinue | Where-Object { $_.ResourceId -like "*/resourcegroups/$ResourceGroupName/*/labs/$Name"}

Unfortunately calling Get-AzureRmResource with only a resource type wasn't supported until a later version of powershell (once they got rid of the Find-AzureRmResource commandlet).

We need to decide if we require Azure Powershell 6.x or newer (or Azure Powershell Core 1.x or newer), or if we should make the library compatible with Azure Powershell 5.x...

**Comment by lucabol** [comment]
Fixed in #496 by adding test for version. We don't work in 4.X.
