### ISSUE TITLE
[AZ.DEVTESTLABS] Library doesn't allow querying for VMs in a "Failed" state

### ISSUE THREAD

**Issue by petehauge** [Azure/azure-devtestlab#495]
![libraryerror](https://user-images.githubusercontent.com/12090616/58667318-ac473880-8303-11e9-9c22-212b5fc6fb34.png)

The DTL PowerShell library currently doesn't support querying for VMs in a **'failed'** state, we should add this.

**Comment by lucabol** [comment]
Fixed in #496
