### ISSUE TITLE
windows-visualstudio artifact puts extra args on the cmd line - causes duplicates

### ISSUE THREAD

**Issue by PhilLee-MSFT** [Azure/azure-devtestlab#502]
This artifact installer adds additional cmdline args that can cause duplicates which causes the VS installer to error out.  The extra args might be OK if the user didn't also supply some.  Or, the installer could search the user's cmdline and not add duplicates.

**Comment by leovms** [comment]
Thank you for reporting this issue. Can you please provide an example that causes it? We'll look into it and get back to you.

**Comment by PhilLee-MSFT** [comment]
The easiest param that causes a problem is -includeRecommended, but there could be others.  Looking at the code of the installer, you can see that cmdline options are being added.  That should only happen if the  user doesn't supply args.  Though this type of change won't be backward compatible.

**Comment by leovms** [comment]
@PhilLee-MSFT, I've made the necessary changes as part of PR #510.

**Comment by leovms** [comment]
I've merged the code changes. If there are other issues, feel free to ping me.
