### ISSUE TITLE
PowerShell Command naming in docs uses aliases rather than actual names. 

### ISSUE THREAD

**Issue by ChrisLGardner** [Azure/azure-devtestlab#506]
~~The standard naming for PowerShell commands is Verb-Noun, so Dtl-NewLab should actually be New-DtlLab.~~

~~Not following these standards makes it harder for users to learn the commands and requires them to look it up each time they want to use them. The goal should always be to lower the barrier to entry and make adoption easier.~~

~~Is there a reason it was chosen to move away from this format? Do you have an Open Api spec that could be put through the AutoRest project that the other Az modules are using, this would ensure that the naming and format is standardised more inline with both Az and with PowerShell as a whole.~~

Edit: looks like the module is actually built correctly but your docs are using some aliases. The docs should always reflect the actual PowerShell commands, again to ease user adoption. https://github.com/Azure/azure-devtestlab/blob/master/samples/DevTestLabs/Modules/Library/HowTo.md

**Comment by lucabol** [comment]
Hi Chris,
Thanks for logging this. It's a work item we are aware of and will fix at some point.

**Comment by lucabol** [comment]
Fixed in 3effa424b47fcc6a0bee4b8aaf0f662626b48d19
