### ISSUE TITLE
VS Code Artifact - Breaking Change

### ISSUE THREAD

**Issue by rgrwatson85** [Azure/azure-devtestlab#513]
#503 is a breaking change for those that use VS Code as a mandatory artifact as it added a required parameter and mandatory artifacts must be parameterless.

**Comment by leovms** [comment]
Acknowledged. Working on reverting the changes.

**Comment by leovms** [comment]
@rgrwatson85, please try it again and report back.

**Comment by rgrwatson85** [comment]
@leovms - that fixed it! Is than plan then to create a 64-bit artifact?

**Comment by leovms** [comment]
I'm going to bring it up to the team and have an internal discussion. We should be resilient to such breaks changes. Thank you for taking the time to report it. I'll go ahead and close the issue.

**Comment by leovms** [comment]
@rgrwatson85, I just did an internal test. I think I know what introduced the breaking change. I'm running a quick test to confirm. I may be able to introduce the parameter safely, just by removing the `allowEmpty` flag. If I make the change, are you willing to try it again?

**Comment by rgrwatson85** [comment]
@leovms - absolutely

**Comment by leovms** [comment]
So far, every scenario I tried seems to work for backward compatibility. Can you tell me where you see an error? Are you seeing it when you execute the creation of a VM? I did the following to test:
- Set up a lab with Mandatory artifacts, using the version of the artifact before changes.
- Created a lab VM and checked the status of the application of the mandatory artifact. It worked.
- Modified the artifact and added the new parameter with a default value. Create a lab VM. It worked.
- Updated the artifact to have the `"allowEmpty" = false` flag set. Created a lab VM. It worked.

All Mandatory Artifact scenarios above have worked. Can you give me some more details to repro the issue?

**Comment by rgrwatson85** [comment]
The failure happens when updating via a PUT request to the REST endpoint for the lab. https://docs.microsoft.com/en-us/rest/api/dtl/labs/createorupdate

**Comment by leovms** [comment]
Right. So we fail at the lab validation. Thanks for the confirmation.

**Comment by rgrwatson85** [comment]
Thanks for the quick turnaround @leovms. Much appreciated!
