### ISSUE TITLE
while creating VM Add proxy file missing in Add Artifacts page 

### ISSUE THREAD

**Issue by KasireddyAlekhya** [Azure/azure-devtestlab#549]
I am Creating VM's in VSTS-DTL-AGILETESTING . I am not able to Add proxy in Artifacts page.

Steps : 
Open the below link 

https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/866f6b4c-09b5-4ba0-b5fc-c2a1f8d740c1/resourceGroups/AutomatedTesting/providers/Microsoft.DevTestLab/labs/Automated-Testing/overview

Click on Add button.
Enter all the information i.e. VM name ,userid and password.
Click on Add/Remove Artifacts link.
Search for Proxy File

Expected Result: Proxy File should add successfully .

Actual : No Artifacts found .

NOTE: I can't install Visual Studio in VM without this proxy .
please file Attachment for more information
![ArtifactsError](https://user-images.githubusercontent.com/44359532/62757925-74463980-ba9a-11e9-8086-4e002d798aa0.PNG)

**Comment by leovms** [comment]
Please post bugs either on our [MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=AzureDevTestLabs&filter=unanswered&sort=lastpostdesc) or through a support ticket.

To create a support ticket, from the Azure Portal, navigate to your lab and then go to "Diagnose and solve problems". On that page, there's a link to generate a "support request".
