### ISSUE TITLE
Failed to create public environment of "Web App with PostgreSQL" in DTL

### ISSUE THREAD

**Issue by callentan** [Azure/azure-devtestlab#580]
**Steps to reproduce:**
Use a DTL in public (regions supported)
Create a instance using the public environment "Web App with PostgreSQL";
Check the deployment response.

**Expected Behavior:**
Public environment is healthy.

**Actual Behavior:**
1. The API version for creating resource of "Microsoft.DBforPostgreSQL/servers" is not supported.
![image](https://user-images.githubusercontent.com/39490917/66916537-fc722d80-f04d-11e9-94fd-9db655d97efd.png)
Refer to: Environments/WebApp-PostgresSQL/azuredeploy.json   Line79

2. If I use such recommend version of API (build a private ARM), another error will threw:
![image](https://user-images.githubusercontent.com/39490917/66916541-0005b480-f04e-11e9-912c-183dfc40d1f6.png)
Refer to: Environments/WebApp-PostgresSQL/azuredeploy.json   Line26

**Comment by leovms** [comment]
The template has been updated.
