### ISSUE TITLE
Chocolately Minimum support for TLS 1.2

### ISSUE THREAD

**Issue by alistairl** [Azure/azure-devtestlab#612]
The Chocolately based Windows Artifacts check for and download install.ps1 from https://chocolately.org/install.ps1.

When I ran this recently on Windows Server 2016 it failed with error ERROR: Exception calling "DownloadString" with "1" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."

https://chocolately.org appears to support only TLS 1.2 and TLS 1.3 so I worked around the above by setting the security protocol to TLS 1.2. I did this by applying the following before the download line:

[Net.ServicePointManager]::SecurityProtocol = "tls12"

I'm not raising a pull request as I've not tested this on other Operating Systems and I don't know if there is a better / preferred way to set the protocol.

**Comment by marty-macfly** [comment]
Hello,

Same issue for me on a Windows 2012 R2 and your work around is working for me.

**Comment by leovms** [comment]
Thank you for bringing this up. I'll take a look and update all necessary artifacts.

**Comment by leovms** [comment]
Please look at PR #613. Let me know if there's anything I may have missed.

**Comment by alistairl** [comment]
With my limited tooling that looks awesome. I hadn't noticed that a similar change had to be made last year for other domains. Now that I actually looked there was advance notice at https://chocolatey.org/blog/remove-support-for-old-tls-versions.

Awesome turnaround speed!

**Comment by leovms** [comment]
@alistairl, we just merged the changes. Can you please check again on your side to make sure the artifact is now behaving as expected?

**Comment by marty-macfly** [comment]
It's working for me after your change.

**Comment by leovms** [comment]
Thank you all.
