### ISSUE TITLE
Az.LabServices module is not Published to the PowerShell Gallery

### ISSUE THREAD

**Issue by kilasuit** [Azure/azure-devtestlab#619]
Is there a reason why this module hasn't been published to the PowerShellGallery? https://www.powershellgallery.com

Is this something that can then be published at all?

**Comment by lucabol** [comment]
Hi Ryan,
We have been talking with the Az module guys to have it published there. If that doesn't come to fruition, your suggestion is a very good one.

**Comment by kilasuit** [comment]
Any update on this at all?

**Comment by lucabol** [comment]
Hi Ryan,
Thanks for following up. We had more discussions about integrating this into the Az module. We might (no promises though) be able to go that way. If that fails we will reconsider your proposal, as it seems very logical. We'll get back on the thread once we have something more official to announce.

**Comment by lucabol** [comment]
Hi @kilasuit, just wanted to follow up on this. We are still working on integrating this into the official Az module. Unfortunately, no fixed release date yet.

**Comment by kilasuit** [comment]
Thanks for following up and providing an update @lucabol 😊

I'll look forward to seeing this get integrated sometime in the future.

**Comment by RogerBestMsft** [comment]
The April 2022 Update (preview) is in the gallery.  https://www.powershellgallery.com/packages/Az.LabServices/0.1.0

**Comment by kilasuit** [comment]
Glad to see this finally happen - thanks for making it happen @RogerBestMsft, @lucabol and rest of the team!

**Comment by lucabol** [comment]
It's all @RogerBestMsft . I am just a bystander. Sorry it took so long.
