### ISSUE TITLE
Importing a VM throws a BlobDoesNotExistInStorageAccount error

### ISSUE THREAD

**Issue by flixman** [Azure/azure-devtestlab#645]
I have a VM I am trying to import from one lab into another. Labs belong to different subscriptions, owned by the same tenant. This is the error I am getting after 1 h of the script going on:

Invoke-AzResourceAction: BlobDoesNotExistInStorageAccount : The blob name: <VM Data disk> was not found in the lab storage account: <Storage Account in new lab>, container: datadisks
Write-Error: Failed to migrate VM '<VM Name>' from Lab '<Old DTL>' to Lab '<New DTL>'.

**Comment by leovms** [comment]
@flixman, which script are you running? Can you elaborate? From the error message it appears like the VM and Lab names are not provided or determined at runtime.

**Comment by flixman** [comment]
@leovms Sorry, my bad: the script I am referring to is [ImportVirtualMachines_ps6.ps1](https://github.com/Azure/azure-devtestlab/tree/master/samples/DevTestLabs/Scripts/ImportVirtualMachines). I have checked that I have contributor permissions on the destination Storage account.

**Comment by flixman** [comment]
@leovms Is there anything else I can help with? I need to import a number of machines, and this issue is really blocking me :s Is there any workaround I can use while this is being investigated?

**Comment by leovms** [comment]
@flixman, I would need to repro your issue. Can you provide sample parameters you are passing? It is not necessary that you give concrete values for subscription ID, for example. I just need the pseudos of the values you pass. Also, does the image you are trying to import have data disks?

**Comment by joerage** [comment]
We discovered this to be a product bug. The fix has since been deployed. Sorry for the inconvenience.
