### ISSUE TITLE
Windows-Chrome artifact fails to install

### ISSUE THREAD

**Issue by TCourtneyOwen** [Azure/azure-devtestlab#659]
Over the past couple days I have been hitting the following error when trying to deploy the [Windows Chrome artifact](https://github.com/Azure/azure-devtestlab/tree/master/Artifacts/windows-chrome) on our Azure VMs::

Validating parameters.
Configuring PowerShell session.
Ensuring latest Chocolatey version is installed.
Preparing to install Chocolatey packages: googlechrome.
Chocolatey v0.10.15
Installing the following packages:
googlechrome
By installing you accept licenses for the packages.

chocolatey-core.extension v1.3.5.1 (forced) [Approved]
chocolatey-core.extension package files install completed. Performing other installation steps.
 Installed/updated chocolatey-core extensions.
 The install of chocolatey-core.extension was successful.
  Software installed to 'C:\ProgramData\chocolatey\extensions\chocolatey-core'

GoogleChrome v81.0.4044.138 (forced) [Approved]
googlechrome package files install completed. Performing other installation steps.
Downloading googlechrome 64 bit
  from 'https://dl.google.com/tag/s/dl/chrome/install/googlechromestandaloneenterprise64.msi'

Download of googlechromestandaloneenterprise64.msi (60.46 MB) completed.
Error - hashes do not match. Actual value was '10570B6B3931CCE7F13763FD4F1AC7075E3036A38F13EDC2754C9894D2114B9F'.
ERROR: Checksum for 'C:\windows\TEMP\chocolatey\GoogleChrome\81.0.4044.138\googlechromestandaloneenterprise64.msi' did not meet '2566c802687c014aa7e89bce14de3cb7ed119da8a0374c9a7eb37b4bc3b0dc0a' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of googlechrome was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\GoogleChrome\tools\chocolateyInstall.ps1'.
 See log for details.
googlechrome not installed. An error occurred during installation:
 Stopping further execution as googlechrome has failed install.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 Could not find a part of the path 'C:\ProgramData\chocolatey\lib\GoogleChrome\.chocolateyPending'.
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 Could not find a part of the path 'C:\ProgramData\chocolatey\lib\GoogleChrome\.chocolateyPending'.
Maximum tries of 3 reached. Throwing error.

Chocolatey installed 0/0 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Did you know the proceeds of Pro (and some proceeds from other
 licensed editions) go into bettering the community infrastructure?
 Your support ensures an active community, keeps Chocolatey tip top,
 plus it nets you some awesome features!
 https://chocolatey.org/compare
Could not find a part of the path 'C:\ProgramData\chocolatey\lib\GoogleChrome\.chocolateyPending'.

ERROR: Installation failed (-1). Please see the Chocolatey logs in %ALLUSERSPROFILE%\chocolatey\logs folder for details.

The artifact failed to apply.

Is this a known issue?  

Thanks,

Courtney

**Comment by leovms** [comment]
@TCourtneyOwen, the issue seems to point to the underlying package coming from the Chocolatey repo (see [comments](https://chocolatey.org/packages/GoogleChrome)). It looks like we need to wait until it is fixed at the source.

Alternatively, if you trust the installer, you can install the same package using the **Install Chocolatey Packages** artifact instead.

![image](https://user-images.githubusercontent.com/14631204/82716544-fa1c2580-9c65-11ea-8aef-eeb099a896fa.png)

**Comment by TCourtneyOwen** [comment]
@leovms That works!  Thanks
