### ISSUE TITLE
Join Active Directory (AD) domain

### ISSUE THREAD

**Issue by githubsteveb** [Azure/azure-devtestlab#667]
Hey guys,

Anyone been able to use the 'Join Active Directory (AD) domain' artifact? I've tried a couple times in 2 different labs but always fails out.

```
Name: Join Active Directory (AD) domain
Repository: Public Artifact Repo
Status: Failed
Install Time: Fri Jun 12 2020 15:24:08 GMT+0100 (British Summer Time)
```

Deployment Message

> Attempting to join computer PAW-PC-01 to domain blah.com.
> ERROR: Computer 'PAW-PC-01' failed to join domain 'blah.com' from its current workgroup 'WORKGROUP' with following error message: The system cannot find the file specified.
> Artifact failed to apply.

Extension Message
>Attempting to join computer PAW-PC-01 to domain blah.com.
ERROR: Computer 'PAW-PC-01' failed to join domain 'blah.com' from its current workgroup 'WORKGROUP' with following error message: The system cannot find the file specified.
Artifact failed to apply.

Then if i rdp onto that machine, run the powershell join, it works as expected.
`add-computer -domainname blah.com –credential blah\domainjoiner -restart –force`

Thanks!

Steve

**Comment by leovms** [comment]
@githubsteveb, it is likely that you're specifying a value for OU that is not correct. Either, don't use a value for OU (blank is fine), or validate that the OU is well-formed.

**Comment by githubsteveb** [comment]
> @githubsteveb, it is likely that you're specifying a value for OU that is not correct. Either, don't use a value for OU (blank is fine), or validate that the OU is well-formed.

haha! you are right. I blanked off the OU and the new server deployment joins as expect :) Thanks @leovms  - have a groovy weekend.
