### ISSUE TITLE
It seems param WaitMinutesForApplyArtifacts in task AzureDtlCreateVM not working for me

### ISSUE THREAD

**Issue by simen-wu** [Azure/azure-devtestlab#672]
I integrate task AzureDtlCreateVM (javascript version) in my yaml build pipeline. My template takes long time (more than 1 hour) to apply artifacts during the creation of virtual machine. So I specify task parameter WaitMinutesForApplyArtifacts with value "240". That means 4 hours. However, after around 55 minutes, while the artifacts are still being applied on the vm, the task already returns successfully and the pipeline then completes.

**Comment by leovms** [comment]
@simen-wu, sorry for the delay responding. To clarify, the `WaitMinutesForApplyArtifacts` only happens after the ARM template deployment returns. It does not control the timeout period of the ARM template deployment itself, nor the timeout of the task in the pipeline. You may want to check the timeout default for tasks in your pipeline.
