### ISSUE TITLE
Devtest labs VM creation folder

### ISSUE THREAD

**Issue by arunricky** [Azure/azure-devtestlab#673]
I am not sure if this is the right place to ask question as the question is regarding Devtest labs creation using API in Azure logicapp. I am trying to create a lab and the lab is getting created ok however I want all VMs to be created in same RG as the devtest lab. The devtest lab creation process is running ok and there is no error however the location for VMs is not updated in labs.
![image](https://user-images.githubusercontent.com/40566250/85829386-d781ad00-b7cd-11ea-9e1a-c1a0887bc079.png)

Thanks for help, apologies if this is not the right forum to ask APIs related question, if anyone can direct me to correct location that would be helpful.

**Comment by petehauge** [comment]
It looks like the property name is incorrect in your screenshot - thanks for all the detail!  Can you try "vmCreationResourceGroupId" instead?  (missing the "Id" at the end of the JSON property)  Thanks!

**Comment by arunricky** [comment]
Thanks @petehauge , Tried both "vmCreationResourceGroup" and "vmCreationResourceGroupId" but still no luck.

**Comment by petehauge** [comment]
Oh, sorry I missed it the first time I looked, you also need to use a newer API version.  The feature for specifying the resource group for the VMs came after the API version you have listed.  Could you try with the "2018-10-15-preview" API version?  (it's specified in the URI)

**Comment by arunricky** [comment]
Great, it did work with new API version.
Last one must be limited in some configurations

Thanks a lot.
