### ISSUE TITLE
How to set Classroom labs rbac using python sdk

### ISSUE THREAD

**Issue by Stijnc** [Azure/azure-devtestlab#687]
Currently we are deploying labs into existing accounts per department.
When somebody requests a lab, the lab is provisioned, but how can we make the requestor the lab owner?
I did not find how to do this in neither PowerShell or the python SDK.

Could you elaborate?

**Comment by EMaher** [comment]
@Stijnc,

Making someone a lab owner requires the typical Azure role assignment calls.  For PowerShell, see [role assignments in PowerShell](https://docs.microsoft.com/azure/role-based-access-control/role-assignments-powershell). 

To make someone the owner on just a single lab, they will need Reader access on the lab account and Owner access on the lab itself.  There is an example how to do this at [create ethical hacking course script](https://github.com/Azure/azure-devtestlab/blob/086ae219c3da2948b1a67be77cd49ecb0e9ed384/samples/ClassroomLabs/Scripts/EthicalHacking/Create-EthicalHacking-LabsAccount.ps1#L105-L108).

Hope that helps,
Elizabeth

**Comment by EMaher** [comment]
It's been a while since I posted the answer, so I'm assuming this question has been answered.  @Stijnc, please post a question to the forums at https://techcommunity.microsoft.com/t5/azure-lab-services/bd-p/AzureLabServices if you are still having issues.
