### ISSUE TITLE
Error when using ConvertTo-SecureString in Azure DevTest Labs Create VM task (version 3) 

### ISSUE THREAD

**Issue by hungwenc** [Azure/azure-devtestlab#691]
In Azure DevTest Labs Create VM task (**version 2**),

I put below code in the **Template Parameters**,

`-userName '$(vmUserName)' -password (ConvertTo-SecureString -String '$(vmPassword)' -AsPlainText -Force) -labName 'AzureIaaSVM' -size 'Standard_D8s_v3'`

And it runs successfully. 

But when I change to use **version 3**, and put above command in **Parameter Overrides**

I got this error 

`##[error]Error => code: 'InvalidDeploymentParameterValue'; message = 'The value of deployment parameter 'AsPlainText' is null. Please specify the value or use the parameter reference. See https://aka.ms/resource-manager-parameter-files for details.' "`

Then I change the code to 

`-userName '$(vmUserName)' -password (ConvertTo-SecureString -String '$(vmPassword)' -AsPlainText 'None' -Force 'None') -labName 'AzureIaaSVM' -size 'Standard_D8s_v3'
`

But still not work. The error is 

`##[error]Error => code: 'InvalidTemplate'; message = 'Deployment template validation failed: 'The template parameters 'String, AsPlainText, Force' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'newVMName, labName, size, userName, password'. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'.'
`

Is there any suggested way to fix this error?

**Comment by leovms** [comment]
@hungwenc, you don't need to do this. To ensure your PAT is secure, just add it to your pipeline definition under `Variables` and enable the padlock named `Change variable type to secret`. Then, pass it to the task without using a secure string, just like any other variable. The value will be automatically protected in transit and will not appear as an environment variable like it does for non-secret variables.
