### ISSUE TITLE
Get-AzLab UserQuota always returns 400

### ISSUE THREAD

**Issue by Owen-Davies** [Azure/azure-devtestlab#704]
UserQuota in a Lab always returns 400, even if you update using the REST api directly.

The documentation isn't clear what UserQuota is:
![image](https://user-images.githubusercontent.com/6824246/93577686-449f7b80-f994-11ea-9843-90c1f57c9ba7.png)

properties.userQuota Description says "Maximum value MaxUsersInLab can be set to, as specified by the service", but properties.maxUsersInLab seems the correct property for this description.

I've tested creating a new Lab using New-AzLab and tried to set userQuota, and it creates the Lab with userQuota property set to 400, but sets the usageQuota correctly. New-AzLab uses the /createLab REST api, but the documentation above doesn't include details for /createLab it only has the details for /labaccounts/{labAccountName}/labs/{labName} which it says is the Create and Update method. 

API version in the documentation is 2018-10-15, so obviously is outdated anyway.

If I update the Lab using Set-AzLab which uses the usageQuota property, it updates usageQuota correctly, and still returns 400 from userQuota.

**Comment by nicolehaugen** [comment]
Logged product bug to track this issue.

**Comment by EMaher** [comment]
@Owen-Davies,

The property names are confusing, so let me go through each with a little more detail as see if that helps.  Answers are based on the '2019-01-01-preview' version of the api.

**_Microsoft.LabServices/labAccounts/labs_**
**properties.usageQuota** - This is a constant that describes the maximum number of users that will ever be allowed in a lab.  This number is set by the Lab Services services itself.  It is _not_ related to 'properties.userQuota'.
**properties.maxUsersInLab** - This is a property that describes the maximum number of user that can register for the lab.  It will also be equal to the number of VMs  that will be available in the VM pool.  Property can not be set higher than 'properties.usageQuota'.
**properties.userQuota** - This is a property that describes the default time a student gets for 'quota time' (i.e. homework time).  It does not account for any additional quota time an individual student is given.  
**_Microsoft.LabServices/labAccounts/labs/users_**
**properties.additionalUsageQuota** - This is property specifies the amount of extra quota time (i.e. homework) on an individual student basis.  Total quota time allowed for a student is 'labs.properties.userQuota' + 'labs.user.properties.additionalUsageQuota'.  This property is _not_ related to the 'labs.properties.usageQuota'.
**properties.totalUsage** - This is a read-only property that specifies the total amount of time the student has used the VM against their allotted quota.  This does not include scheduled time the student has used the VM.  The maximum value this property will be is  'labs.properties.userQuota' + 'labs.user.properties.additionalUsageQuota'. 

I hope this explanation clarified what each property is used for.  Please let me know if you have further questions. Like @nicolehaugen mentioned, she logged a suggestion against a future api version regarding the confusion around what each property is used for.
