### ISSUE TITLE
Size limit for file in artifact?

### ISSUE THREAD

**Issue by YuqingZhao** [Azure/azure-devtestlab#712]
We are considering upload some big files to simplify the deployment. We have read the article [https://social.msdn.microsoft.com/Forums/en-US/1b1b6a6c-b93c-418d-96a8-cd22df9fc7f4/size-limit-added-to-artifact-payload](url) but the question remains - Is there any actual size limit for file in artifact?

**Comment by leovms** [comment]
DTL does not have a hard limit on artifact content sizes. However, you should consider a few other things before going that route. I'll re-iterate with more detail what is already indicated in the post you referenced.
- The artifact folder is cached in the lab's storage account to allow access to the artifact from the VM. No direct access from the VM to the private repo ever happens.
- The interaction with the storage account may have limitations you may hit. Refer to the storage account docs for any documented limitations.
- The artifact is applied via an ARM template. This deployment has a hard timeout of 90 minutes. So, if the file is too large, it may take too long to download and leave your artifact little time to complete any remaining tasks.

I suggest you consider the following instead:
- Store the files in a centrally managed location that can be accessed from the VM.
- Configure a user-assigned managed identity to access the files.
- Configure the user-assigned managed identity in the lab.
- Author one artifact to download the files and place them in a well-known location in the VM.
- Author another artifact to leverage the downloaded files.
