### ISSUE TITLE
How To Add Azure DevTest Lab VM to Azure Update Management

### ISSUE THREAD

**Issue by ajayvarma560** [Azure/azure-devtestlab#716]
Hello Team,

How windows patching works in Azure DevTest Lab VM's.

Thank's,
Ajay

**Comment by leovms** [comment]
Can you elaborate? Are you referring to running Windows Updates? If so, you can try using artifact [Install the latest Windows Updates](https://github.com/Azure/azure-devtestlab/tree/master/Artifacts/windows-install-windows-updates).

**Comment by ajayvarma560** [comment]
I have a set of windows vms in DevTest Labs those should be added to azure update management so that I can push updates to VM's in schedule basis.

**Comment by leovms** [comment]
DTL does not have direct support for that. However, you can configure the backing Azure VMs like any other VM. Refer to the [Update Management](https://docs.microsoft.com/en-us/azure/automation/update-management/overview) documentation.
