### ISSUE TITLE
Feature Request: Set-AzLabUser Additional Usage Quota

### ISSUE THREAD

**Issue by thecodeprofessor** [Azure/azure-devtestlab#729]
The ability to change a user's individual quota would be very helpful when managing class of students.

Example: Set-AzLabUser -User $user -AdditionalUsageQuota PT2H

**Comment by nicolehaugen** [comment]
This should be addressed when we merge in changes recently made from private repo.  @petehauge  - please  #confirm this once merge is done.

**Comment by EMaher** [comment]
This change has been added in commit 1e8a527f1a648e44ab3e296b7989b1f267c5454c
