### ISSUE TITLE
Feature Request: I want to set a Japanese string in Notes in New-AzLabSchedule function

### ISSUE THREAD

**Issue by tomaeda** [Azure/azure-devtestlab#745]
When I sending Japanese string as a Notes element to The New-AzLabSchedule function, On a set schedule notes is '???'.
When using Japanese string in Invoke-WebRequest, it is necessary to send it with utf-8 character code.
I want an option that can specify a character code.

**Comment by nicolehaugen** [comment]
Added to our planner for tracking.

**Comment by RogerBestMsft** [comment]
Moved to https://github.com/Azure/LabServices/issues/1
