### ISSUE TITLE
Updating a system during Artifact execution can 'hang' Azure DevTest agent

### ISSUE THREAD

**Issue by d3r3kk** [Azure/azure-devtestlab#75]
When working with system package management tools, a bug with the azure tools (or rather, a bug with the process being reset and not recovering from that reset) was encountered. 

When updating the system using `yum update --assumeyes --quiet` command from within an Azure DevTest artifact (specifically the yum artifact - see my pull request #74 ), the Windows Azure Linux Agent gets restarted in specific instances (probably a package that the Windows Azure Linux Agent service depends on gets updated, and therefore a restart of the agent is performed during the command).

The bug is that the agent after being restarted doesn't pick up where it left off and finish the rest of the artifact's process. The symptom is on the Azure DevTest Labs blade, the VM with the artifact applied to it never finishes installing all of the artifacts it was given, and there doesn't seem to be a way to reset the status of the VM.

> The log messages from /var/log/messages that point to the reset of the Azure Linux Agent Service:
>    Apr 29 06:12:39 localhost systemd: Stopping Windows Azure Linux Agent...
>    Apr 29 06:12:39 localhost systemd: Started Windows Azure Linux Agent.
>    Apr 29 06:12:39 localhost systemd: Starting Windows Azure Linux Agent...
### Procedure:
1. Log into the Azure portal and navigate to Azure DevTest Labs, and enter an existing lab instance (create one if one does not exist).
2. Click on '+ Lab VM' button at the top of the Azure DevTest Labs blade.
3. Choose the Linux image named 'CentOS-based 7.2'.
4. Fill in the settings for the new Lab VM, username, password, etc...
5. Click on the 'Artifacts >' button in the Lab VM blade, opening the Add Artifacts blade.
6. Choose the Yum Artifact
7. Enter 'git vim' (no quotes) in the 'Packages' text field.
8. Ensure 'true' (no quotes) is set in the 'Run Update First' text field.
9. Leave the 'Additional Options' field blank.
10. Click Add, the Add Artifact blade will close
11. In the Add Artifacts blade, click OK
12. In the Lab VM blade, click Create
13. The lab Vm will begin being created.
### Expected Result:

The lab VM will be created, and the packages updated on the machine with the desired extra packages installed.
### Observed Result:

The lab VM will never progress past the status 'Installing 1/1 Artifacts'
### Further Observations:

Log into the machine once it gets to the status 'Installing 1/1 Artifacts'

Get root priviledges on the machine

> sudo su

List the latest messages in the system log and pull out the Azure DevTest Yum Artifact messages:

> cat /var/log/messages | grep AZDEVTST
>   ...
>    AZDEVTST_YUMPKG[n]: Updating the system using yum update. Command line being used is: 'yum --assumeyes --quiet update'.
> ...this means that the last message in the log thus far is that yum update was being executed on the machine.

List the latest messages in the system log and pull out Azure Service messages

> cat /var/log/messages | grep "Azure Linux Agent"
>     Apr 29 06:44:06 localhost systemd: Started Windows Azure Linux Agent.
>     Apr 29 06:44:06 localhost systemd: Starting Windows Azure Linux Agent...
>     Apr 29 06:47:35 localhost systemd: Stopping Windows Azure Linux Agent...
>     Apr 29 06:47:35 localhost systemd: Started Windows Azure Linux Agent.
>     Apr 29 06:47:35 localhost systemd: Starting Windows Azure Linux Agent...
> ...note that the Azure Linux Agent was started (at system startup presumably), stopped, then started again!

List all the messages and note where the stop/start cycle of the Azure Linux Agent occurs in relation to the yum update task run by the Yum Artifact.

**Comment by ericame** [comment]
Hi @d3r3kk, this issue no longer repos. Please let me know if you are still seeing issues.

Thanks,
Erica
