### ISSUE TITLE
Azure Lab Services cmdlets should include Peering parameters

### ISSUE THREAD

**Issue by nyanhp** [Azure/azure-devtestlab#751]
The REST API and the Portal expose the option to enable peering on a Lab Account. The `AzLab` cmdlets should include these parameters as well. Parameters in question would be `VirtualNetworkAddressRange` and `VirtualNetworkName` (the API uses the virtualNetworkResourceId which is not great as a cmdlet parameter). Internally, the cmdlet would validate if the network exists and if the address range is valid.

**Comment by nicolehaugen** [comment]
Added to planner for tracking.

**Comment by RogerBestMsft** [comment]
The new PowerShell module https://www.powershellgallery.com/packages/Az.LabServices/0.1.0 includes the properties for the vnet injection.
