### ISSUE TITLE
Unable to schedule labs in Australia Time using TimeZoneId param

### ISSUE THREAD

**Issue by slape** [Azure/azure-devtestlab#753]
I'm using `New-AzLabSchedule` to schedule labs over the following timezones:
Arizona
Central
Eastern
Mountain
Pacific
Perth
Sydney

My code block for the scheduling call is:

$params = @{
        TimeZoneId  = $messageHashTable.time_zone
        FromDate    = $messageHashTable.date
        ToDate      = $messageHashTable.date
        StartTime   = $startTime
        EndTime     = $endTime
        Notes       = $notes
        }
    
    $labObj = Get-ClassLab($messageHashTable)
    New-AzLabSchedule -Lab $labObj @params

The above code works perfectly if `TimeZoneId` is given the strings 'Pacific Standard Time' or 'Eastern Standard Time' but if it is given 'Australian Eastern Standard Time' or 'Australian Western Standard Time' it breaks with the following error:

{"error":{"code":"InvalidTimeZone","message":"Property TimeZoneId must be a valid time zone."}}

**Comment by slape** [comment]
Time Zone Strings from this list seem to work: https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/timezones-overview

Maybe this issue should be a documentation issue?

**Comment by nicolehaugen** [comment]
Added to planner for tracking.

**Comment by EMaher** [comment]
It looks like the api accepts Windows time zone ids.  Full list is at [https://docs.microsoft.com/en-us/rest/api/maps/timezone/get-timezone-enum-windows](https://docs.microsoft.com/en-us/rest/api/maps/timezone/get-timezone-enum-windows).   For example, Perth would be 'W. Australia Standard Time'.

I'll add some documentation to the how-to and module before closing this bug.

**Comment by EMaher** [comment]
Documentation updates merged.
