### ISSUE TITLE
Pipelines Agent artfact fails with ERROR: Connecting to remote server localhost failed

### ISSUE THREAD

**Issue by nikydobrev** [Azure/azure-devtestlab#757]
I'm trying to use the Pipelines Agent artifact (windows-vsts-build-agent) to set up a new agent.

The artifact installation fails with the following error message:

Validating parameters
Preparing agent installation location
Checking for a previously configured agent
Downloading agent package
Extracting agent package contents
Getting agent installer path
Installing agent
ERROR: Connecting to remote server localhost failed with the following error message: The client cannot connect to the destination specified in the request. Verify that the service on the destination is running and is accepting requests. Consult the logs and documentation for the WS-Management service running on the destination, most commonly IIS or WinRM. If the destination is the WinRM service, run the following command on the destination to analyze and configure the WinRM service: "winrm quickconfig". For more information, see the about_Remote_Troubleshooting Help topic.

Steps to reproduce:

Steps to reproduce:

1) Create a new DevTest Lab
2) Create a VM using the template: "Visual Studio 2019 Community (latest release) on Windows Server 2019 (x64)" Size = Standard_DS2_v2
3) Add the Pipelines Agent artifact and supply the required parameters.

Thanks,
--Nikolay

PS: Screenshot:
![112982047-ab33fc00-9164-11eb-8ea7-df138b85a0e0](https://user-images.githubusercontent.com/6898714/113850583-4d766400-97a3-11eb-8cce-98732026e1f9.png)

**Comment by nikydobrev** [comment]
Simiral issue [https://github.com/Azure/azure-devtestlab/issues/434](url)

**Comment by leovms** [comment]
@nikydobrev, I executed it without problems when I specify the following. BTW, I tried it without specifying an Agent Name as well and it also worked.

![image](https://user-images.githubusercontent.com/14631204/117027294-9221ec00-acca-11eb-9e69-fcd1decc9391.png)
![image](https://user-images.githubusercontent.com/14631204/117031273-6acd1e00-acce-11eb-8653-06a45d8ae879.png)
![image](https://user-images.githubusercontent.com/14631204/117031363-80dade80-acce-11eb-9f93-bc5e3ac71b88.png)

Now, I do see the `undefined` at the very end. I'm not sure where that is coming from, but I don't think it has a negative impact on the execution of the artifact.

Can you provide sample parameters you used to repro the case?

**Comment by nikydobrev** [comment]
Hi, @leovms,

Thanks for looking into the case. If you set the "Enable Autologon" to True it will fail. 


![Web capture_5-5-2021_92025_portal azure com](https://user-images.githubusercontent.com/6898714/117104527-f6a18180-ad84-11eb-92b3-5028785a48d4.jpeg)

![Web capture_5-5-2021_9437_portal azure com](https://user-images.githubusercontent.com/6898714/117105274-56e4f300-ad86-11eb-8c50-9091e046dd06.jpeg)

Regards,
Nikolay

**Comment by leovms** [comment]
@nikydobrev, thank you for the additional info. To make it work in that context, you need to configure WinRM. Apply the `Configure WinRM`.
![image](https://user-images.githubusercontent.com/14631204/117177219-c6ff7300-ad9e-11eb-8f5e-719e7b37a369.png)

**Comment by nikydobrev** [comment]
Thanks, @leovms. I just have some questions related to that artifact, Since we create our VM in a private network in the DevTest Lab it does not have a public IP address, and we cannot provide it through the "Configure WinRM" artifact. Also, how can we get the FQDN of the machine prior to it is being provisioned? Can you provide the parameters that you passed to the artifacts in your example screenshot above? 

![Web capture_5-5-2021_223753_portal azure com](https://user-images.githubusercontent.com/6898714/117199489-ede79480-adf2-11eb-81c5-c511d8635a55.jpeg)


Thanks,
Nikolay

**Comment by leovms** [comment]
@nikydobrev, yes I used the value from `IP address or FQDN`. The problem I see is that you're using a private IP address. `Configure WinRM` will not work with a Private IP Address because by default the command will configure it as Public. So, the firewall rule will not configure. Additionally, even if you ignore that issue, running the agent install will not work because we then get error `Access Denied`. Having said that, you may be able to copy these 2 artifacts to your own private repo and modify them to fit your scenario.

**Comment by nikydobrev** [comment]
Thanks, @leovms for provided the information. I managed to successfully install the artifact once the 'Configure WinRM' artifacts
 is installed before that. 

Just on a side note, do you manage to know why using a 'Visual Studio 2019 with Windows 10 latest' image does not require to install a 'WinRM' artifact, and the "Pipeline agent" artifact is installed successfully even when the "Enable Autologon" is set to True.

Thanks once again for all the help.

Regards,
Nikolay

**Comment by leovms** [comment]
I don't know. It is possible that it is configured by default. But that's just speculation.
