### ISSUE TITLE
How to create a new Lab in Az.LabServices 

### ISSUE THREAD

**Issue by hafoussa** [Azure/azure-devtestlab#779]
I try to create a new Lab in **Azure Lab Services** using the PowerShell module "**Az.LabServices**". For that:

- I created a new resource group.
- I created a new lab account in the RG.
- I chose the "CentOS" image to base the lab on.
- Then I tried the following command:

**_$lab = $labaccount | New-AzLab -LabName DemoLab -Image $img -Size Basic -UsageQuotaInHours 15 -UserName studentvm -Password ***********_**

Unfortunately, it didn’t work.  Attached you will find the error message.

Could you please help me to solve this issue ??

Thanks in advance,

Hafsa

![Capture](https://user-images.githubusercontent.com/12442274/122531344-b12cd100-d01f-11eb-9529-cd92ef543bcc.PNG)

**Comment by petehauge** [comment]
Hi Hafsa - I took a look and the error is because we don't support idle settings on that particular OS.  I'll see about changing the defaults so others don't run into this.

You can find more info about this here:  https://techcommunity.microsoft.com/t5/azure-lab-services/maximize-cost-control-with-new-auto-shutdown-settings/ba-p/1593744  - the supported Linux distributions points to this doc:  https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/diagnostics-linux?tabs=azcli#supported-linux-distributions .

If you update your command like this, it should work:
```powershell
$img = $labaccount | Get-AzLabAccountGalleryImage | Where-Object {$_.Name -like "CentOs*"}
$lab = $labaccount | New-AzLab -LabName DemoLab `
                               -Image $img `
                               -Size Basic `
                               -UsageQuotaInHours 15 `
                               -UserName studentvm `
                               -Password ************* `
                               -idleGracePeriod 0 `
                               -idleOsGracePeriod 0 `
                               -idleNoConnectGracePeriod 0

```

**Comment by hafoussa** [comment]
Hi Petehauge,

Thanks for helping me out. After including the idle settings parameters, it works for me. However, I still have a problem when a try to create a new lab using the Windows OS.  This is the screenshot.

Could you please help me.

Thanks,

Hafsa

![Capture2](https://user-images.githubusercontent.com/12442274/122747609-9068b380-d28b-11eb-8bfa-9872b3199e5d.PNG)

**Comment by petehauge** [comment]
A quick note for the docs, you can find the available sizes in the Admin Guide in case you need it:  https://docs.microsoft.com/en-us/azure/lab-services/administrator-guide 

For the error you're receiving, it looks like the size requested (Basic) isn't supported in the region (France Central).

I wrote a quick script to check and it looks like neither Windows or Linux is available there - do you need to leverage Lab Services in that region?  If so, please open a support request for the team to see if they can allocate capacity.

Here's the script (leverages our PowerShell module at this location:  : https://github.com/Azure/azure-devtestlab/tree/master/samples/ClassroomLabs/Modules/Library )
```powershell
$rg = "Cortex5_rg"
$name = "francetest"

Import-Module .\Az.LabServices.psm1

$la = Get-AzLabAccount -ResourceGroupName $rg -LabAccountName $name
$PricingAndAvailability = Get-AzLabAccountPricingAndAvailability -LabAccount $la

Write-Host "Windows" -ForegroundColor Green
Write-Host "Availability: $($PricingAndAvailability.operatingSystems.Windows.availability)"
if ($PricingAndAvailability.operatingSystems.Windows.availability -ieq "Available") {
    Get-Member -InputObject $PricingAndAvailability.operatingSystems.Windows.sizes | `
        Where-Object {$_.MemberType -ieq "NoteProperty"} | `
        Select-Object -Property @{Name="AvailableSizes"; Expression={$_.Name}}
}

Write-Host "Linux" -ForegroundColor Green
Write-Host "Availability: $($PricingAndAvailability.operatingSystems.Linux.availability)"
if ($PricingAndAvailability.operatingSystems.Linux.availability -ieq "Available") {
    Get-Member -InputObject $PricingAndAvailability.operatingSystems.Linux.sizes | `
        Where-Object {$_.MemberType -ieq "NoteProperty"} | `
        Select-Object -Property @{Name="AvailableSizes"; Expression={$_.Name}}
}

```

When running this against a Lab Account in the France Central OS, I get this:
![image](https://user-images.githubusercontent.com/12090616/122781489-b9298280-d264-11eb-9423-d08b01e54203.png)

And running using a Lab Account in West Europe:
![image](https://user-images.githubusercontent.com/12090616/122781961-2806db80-d265-11eb-95fc-eda6228fd563.png)

**Comment by hafoussa** [comment]
Hi Pete,

Thanks again for your help. 

Yes, we need to leverage Lab Services in the France Central region. 

When I run your script against a Lab Account **(mydemolab)**  in the **France Central** localtion, I get this ( Both **Windows and Linux are available**):

![c10](https://user-images.githubusercontent.com/12442274/122883199-3fb19300-d33d-11eb-9c09-558ade3c7d4d.PNG)
![c11](https://user-images.githubusercontent.com/12442274/122883227-45a77400-d33d-11eb-9843-caaee1760ccb.PNG)

I will open a support request for the team to see what they will propose.

Thank you,

Hafsa
