### ISSUE TITLE
Clone Git Repo extension does not honour space in the Destination path

### ISSUE THREAD

**Issue by tarunaroraonline** [Azure/azure-devtestlab#78]
If the destination path contains a space, the extension takes the path up to that point...

**For example, if you try to clone the git repo to c:\program files\repos it instead copies the repo to c:\program**

Tarun

**Comment by tarunaroraonline** [comment]
However if you pass the destination path with double quotes it honours the space. I would at the least expect the extension to wrap the path in quotes and escape any special characters behind the scene. It's not a blocking issue. Would be great to fix, or at least indicate in the information icon for the field.

**Comment by drwill-ms** [comment]
Thanks for finding and logging the bug, Tarun. One of us will get to it at some point. If you wish, you may create a branch of the repo, fix it, and send a pull request.

**Comment by leovms** [comment]
Creating a PR to add quotes around Destination parameter to ensure spaces are accounted for.

**Comment by leovms** [comment]
Applied fix.
