### ISSUE TITLE
Add Visual Studio 2019 support to artifact windows-visualstudio

### ISSUE THREAD

**Issue by simen-wu** [Azure/azure-devtestlab#789]
We use artifact [windows-visualstudio](https://github.com/Azure/azure-devtestlab/tree/master/Artifacts/windows-visualstudio)  to install Visual Studio on virtual machines. Currently it only supports VS 2015/2017. It'll better if we can use this artifact to install VS 2019 as well.

**Comment by leovms** [comment]
@simen-wu, apologies, it looks like this question was never answered. Thank you for the feedback. We do not have any current plans to add VS 2019 to the artifact. However, if you or someone else reading this thread has taken it upon themselves to modify the artifact, we welcome contributions. Just send out a PR from your own fork and we'll be happy to review any changes.
