### ISSUE TITLE
New-AzLab - set location - Azure Lab Services

### ISSUE THREAD

**Issue by TobiasK32** [Azure/azure-devtestlab#805]
Is it possible to set the location (e.g. westeurope) of a new lab like it can be done in the GUI during the creation? I couldn't find a parameter in the New-AzLab function for this. I have the impression the location is currently inherited from the Azure resource group.

Thanks in advance!

**Comment by lucabol** [comment]
Hi Tobias,
This is not exposed in these APIs at the moment. We are working on creating official APIs for the service and it will be present there (I believe). I close this issue as our focus is on the new APIs. If your deployment is blocked by this, please reopen and we can take another look.
