### ISSUE TITLE
Account permissions necessary to use Az.LabServices.psm1  (QUESTION)

### ISSUE THREAD

**Issue by jharri3470** [Azure/azure-devtestlab#821]
I have been using Az.LabServices.psm1 for some time now.  However, I have only ever been able to get it to work properly using an account with "owner" role in Az directory.  Is there a more restricted role that can be used?  I do a mix of querying to determine what machines are running, and then stopping machines that need to be started or stopped.  I don't do any creation of anything using this module.

**Comment by RogerBestMsft** [comment]
@jharri3470 You can use contributor role to do vm querying and starting or stopping.  Was there a specific role you wanted to use?

**Comment by RogerBestMsft** [comment]
The PowerShell module https://www.powershellgallery.com/packages/Az.LabServices/0.1.0 uses RBAC to determine access.
