### ISSUE TITLE
vsts-build-agent - no longer installs when called through ARM or BICEP since PR881

### ISSUE THREAD

**Issue by andrewgbell** [Azure/azure-devtestlab#883]
https://github.com/Azure/azure-devtestlab/pull/881 @michaelwstark

This appears to have stopped the VSTS Agent installing for us from our bicep and arm templates in devtestlabs.  Had been working for some years before this change on the Friday 27th Oct.  Now all the extensions except this one work, however it seems to fail early on and no install/config happens.

        artifactId: resourceId('Microsoft.DevTestLab/labs/artifactSources/artifacts', labName, 'public repo', 'windows-vsts-build-agent')

We don't get an error in the deployment, but the build agent is never installed or registered.

**Comment by michaelwstark** [comment]
@andrewgbell - I will roll back the change while I investigate the report.  Thank you.

**Comment by andrewgbell** [comment]
Great, thank you.

**Comment by andrewgbell** [comment]
Now working with change reverted.  Thanks @michaelwstark
